### ISSUE TITLE
[🚫 Bug] Unable to download chromedriver for ReleaseQuality.Insider

### ISSUE THREAD

**Issue by c3-WesleyPickering** [redhat-developer/vscode-extension-tester#1071]
### Describe the bug

I'm trying to run tests against the latest Insider version. Latest insider version requires a chromedriver version 118. The url that's currently used in `driverUtil.ts > getChromeDriverVersion` is `https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${majorVersion}`, which doesn't work for anything after 114, so the api throws.

### Steps to reproduce

```Shell
in node.js run

const exTester = new ExTester(undefined, ReleaseQuality.Insider, extensionDir);
await exTester.downloadCode(testVsCodeVersion);
await exTester.downloadChromeDriver(testVsCodeVersion);
```
```


### Logs

```Shell
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/Users/wesleypickering/c3/c3vsce/test/node_modules/got/dist/source/core/index.js:913:31)
    at Request._onResponse (/Users/wesleypickering/c3/c3vsce/test/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/Users/wesleypickering/c3/c3vsce/test/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (/Users/wesleypickering/c3/c3vsce/lib/events.js:629:26)
    at ClientRequest.emit (/Users/wesleypickering/c3/c3vsce/lib/events.js:526:35)
    at origin.emit (/Users/wesleypickering/c3/c3vsce/test/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (/Users/wesleypickering/c3/c3vsce/lib/_http_client.js:693:27)
    at HTTPParser.parserOnHeadersComplete (/Users/wesleypickering/c3/c3vsce/lib/_http_common.js:119:17)
    at TLSSocket.socketOnData (/Users/wesleypickering/c3/c3vsce/lib/_http_client.js:535:22)
    at TLSSocket.emit (node:events:514:28) {name: 'HTTPError', code: 'ERR_NON_2XX_3XX_RESPONSE', timings: {…}, stack: 'HTTPError: Response code 404 (Not Found)
    …2)
    at TLSSocket.emit (node:events:514:28)', message: 'Response code 404 (Not Found)', …}
```

### Operating System

macOs

### Visual Studio Code

1.86-insiders

### vscode-extension-tester

5.6.0

### NodeJS

18.15.0

**Comment by vlad-dargel** [comment]
the same issue with vscode 1.86.0

**Comment by djelinek** [comment]
Kudos @c3-WesleyPickering 👍🏻 

Thank you for your kick-off in PR and for spotting of this issue. Your suggested changes were priceless when fixing this issue.
