### ISSUE TITLE
Test runner crashes if an editor is opened near the end of a test run

### ISSUE THREAD

**Issue by uozuAho** [redhat-developer/vscode-extension-tester#122]
Eg. If I run a single test like this:

```js
it('has one open editor', async () => {
  const editorView = new EditorView();
  const titles = await editorView.getOpenEditorTitles();
  const editor = await editorView.openEditor(titles[0]);
  expect(editor).not.to.be.null;
  console.log(titles[0]);
});
```

The test passes, but mocha throws an exception:

```
Welcome
    √ has one open editor (241ms)

Shutting down the browser
Uninstalling vscode-extension-tester.api-handler...
Extension 'vscode-extension-tester.api-handler' was successfully uninstalled!

  1 passing (9s)

C:\woz\note_searcher2\vscode\node_modules\mocha\lib\runner.js:911
    throw err;
    ^

NoSuchSessionError: invalid session id
    at Object.throwDecodedError (C:\woz\note_searcher2\vscode\node_modules\selenium-webdriver\lib\error.js:514:15)
    at parseHttpResponse (C:\woz\note_searcher2\vscode\node_modules\selenium-webdriver\lib\http.js:519:13)
    at C:\woz\note_searcher2\vscode\node_modules\selenium-webdriver\lib\http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
From: Task: WebElement.findElement(By(css selector, .editor-instance))
    at Driver.schedule (C:\woz\note_searcher2\vscode\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at EditorGroup.schedule_ (C:\woz\note_searcher2\vscode\node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
    at EditorGroup.findElement (C:\woz\note_searcher2\vscode\node_modules\selenium-webdriver\lib\webdriver.js:2057:17)
    at new AbstractElement (C:\woz\note_searcher2\vscode\node_modules\monaco-page-objects\out\components\AbstractElement.js:38:48)    at new ElementWithContexMenu (C:\woz\note_searcher2\vscode\node_modules\monaco-page-objects\out\components\ElementWithContextMenu.js:18:1)
    at new Editor (C:\woz\note_searcher2\vscode\node_modules\monaco-page-objects\out\components\editor\Editor.js:10:9)
    at new TextEditor (C:\woz\note_searcher2\vscode\node_modules\monaco-page-objects\out\components\editor\TextEditor.js:21:1)    
    at EditorGroup.<anonymous> (C:\woz\note_searcher2\vscode\node_modules\monaco-page-objects\out\components\editor\EditorView.js:148:32)
    at Generator.throw (<anonymous>)
    at rejected (C:\woz\note_searcher2\vscode\node_modules\monaco-page-objects\out\components\editor\EditorView.js:6:65) {        
  name: 'NoSuchSessionError',
  remoteStacktrace: 'Backtrace:\n' +
    '\tOrdinal0 [0x0058A923+1550627]\n' +
    '\tOrdinal0 [0x0050A731+1025841]\n' +
    '\tOrdinal0 [0x0048C5BE+509374]\n' +
    '\tOrdinal0 [0x00421377+70519]\n' +
    '\tOrdinal0 [0x004224D0+74960]\n' +
    '\tOrdinal0 [0x00422469+74857]\n' +
    '\tOrdinal0 [0x005242F7+1131255]\n' +
    '\tGetHandleVerifier [0x0062711D+523789]\n' +
    '\tGetHandleVerifier [0x00626EB0+523168]\n' +
    '\tGetHandleVerifier [0x0062E207+552695]\n' +
    '\tGetHandleVerifier [0x0062791A+525834]\n' +
    '\tOrdinal0 [0x0051B82C+1095724]\n' +
    '\tOrdinal0 [0x0052636B+1139563]\n' +
    '\tOrdinal0 [0x005264D3+1139923]\n' +
    '\tOrdinal0 [0x00525455+1135701]\n' +
    '\tBaseThreadInitThunk [0x768A6359+25]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x771A7C24+228]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x771A7BF4+180]\n'
}
```

I can work around this by 'sleeping' at the end of the test:

```js
it('has one open editor', async () => {
  const editorView = new EditorView();
  const titles = await editorView.getOpenEditorTitles();
  const editor = await editorView.openEditor(titles[0]);
  expect(editor).not.to.be.null;
  console.log(titles[0]);

  // workaround
  await new Promise((resolve, reject) => {
    setTimeout(() => resolve(), 1000);
  });
});
```

Some environment details:

Windows OS

Versions:
`vscode-extension-tester: 3.0.1`
`vscode-extension-tester-locators: 1.45.1`
`vscode-extension-tester-native: 3.0.0`
`monaco-page-objects: 1.0.1`

**Comment by jrichter1** [comment]
Sounds like a loose promise. I'll check if some of these methods needs proper synchronization.
