### ISSUE TITLE
[🚫 Bug] Poor stack trace upon test failure

### ISSUE THREAD

**Issue by gpsaraiva** [redhat-developer/vscode-extension-tester#1226]
### Describe the bug

The stack trace when a test fails is very poor. I would like to see the line where the test failed.
Currently I can only see this:

NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".checkMark"}
  (Session info: chrome=114.0.5735.289)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:513:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:740:17)

I have tried to require the mocha-clean module (which appears to fix this issue) on my .mocharc.json file with no success.
Any ideas on how to get this fixed ? 
Thank you

### Steps to reproduce

```Shell
Just force a a test to file with, for instance, an unexisting css locator
```

### Logs

```Shell
no logs
```

### Operating System

macOs

### Visual Studio Code

1.83.0

### vscode-extension-tester

6.0.0

### NodeJS

20.11.1

### npm

10.2.4

**Comment by djelinek** [comment]
Hello, thank you for bringing this up. At the moment I think it is not a bug. The mentioned logs are coming from selenium-webdriver library. I did not found an easy way how to make it more connected and readable.

I will move this issue from bugs to feature request. Hopefully in future we will be able to investigate more.
