### ISSUE TITLE
Cannot click on a button in the navigation group of "view/title" of a custom tree view

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#124]
I am trying to make vscode-extension-tester to click on an icon that I have added to a custom tree view in the side bar into the `navigation` group:
```json
      "view/title": [
        {
          "group": "navigation",
          "when": "view == repositoryTree",
          "command": "obsRepository.addRepositoryFromDistro"
        }
      ],
    // snip
   "commands": [
      {
        "icon": "$(add)",
        "title": "Add a repository from a Distribution",
        "command": "obsRepository.addRepositoryFromDistro"
      }
    ]
```

The actual test looks like this:
``` typescript
    const section = await new SideBarView()
      .getContent()
      .getSection("Repositories");
    await section.getDriver().sleep(500);

    const addDistroButtonLabel = "Add a repository from a Distribution";
    let addDistroButton = section.getAction(addDistroButtonLabel);
    await addDistroButton.getDriver().sleep(500);
    addDistroButton = await addDistroButton.wait();
    await addDistroButton.click();
```
but independently of the sleep times that I add, I always get the following exception:
```
     ElementNotVisibleError: element not interactable
  (Session info: chrome=78.0.3904.130)
  (Driver info: chromedriver=78.0.3904.105 (60e2d8774a8151efa6a00b1f358371b1e0e07ee2-refs/branch-heads/3904@{#877}),platform=Linux 5.6.14-1-default x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/dan/suse/github.com/dcermak/vscode-obs/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.click()
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at ViewPanelAction.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at ViewPanelAction.click (node_modules/selenium-webdriver/lib/webdriver.js:2092:17)
      at Suite.<anonymous> (out/ui-tests/repositoryTreeView/addRepo.test.js:120:31)
      at Generator.next (<anonymous>)
      at fulfilled (out/ui-tests/repositoryTreeView/addRepo.test.js:25:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any idea what could be the issue here? I can also upload the actual code somewhere as the repository is now public.

**Comment by jrichter1** [comment]
VS Code has a habit of hiding the action buttons whenever the view section is not focused. Check if the actions are visible in this case. If not, they should reappear when you move the mouse over the view section.
```typescript
await driver.actions().mouseMove(section).perform()
```

**Comment by dcermak** [comment]
> ```ts
> await driver.actions().mouseMove(section).perform()
> ```

Yes, that did it, thank you so much!

**Comment by jrichter1** [comment]
> VS Code has a habit of hiding the action buttons whenever the view section is not focused. Check if the actions are visible in this case. If not, they should reappear when you move the mouse over the view section.
> 
> ```ts
> await driver.actions().mouseMove(section).perform()
> ```

This should now be the default behaviour.
