### ISSUE TITLE
Explanation/Dialog window blocks the option to be picked

### ISSUE THREAD

**Issue by lgrossma** [redhat-developer/vscode-extension-tester#1285]
### Describe the bug

When trying to access some element for future work, like InputBox.create(), I assume the extension tester "moves the pointer" to the location of the element and due to the "hovering mouse" over the element, it shows a windows with a dialog that blocks access to the element underneath the window. I was also experiencing similar issue with notifications.
<img width="462" alt="Screenshot 2024-04-30 at 10 22 52" src="https://github.com/redhat-developer/vscode-extension-tester/assets/86789336/39b47f15-1332-446f-b6b7-6c0c47a3fdeb">

### Steps to reproduce

```Shell
1. Choose some element that shows information when hovering over it with mouse
2. Dialog window shows up when hovering over the element with mouse
3. Try to access element underneath the dialog window
4. Element is unaccessible

In my case it was this code:
inputBox = await InputBox.create();
await inputBox.selectQuickPick(INPUTS.credentialsQuickPick);
```

### Logs

```Shell
1) Extension cluster-dependant UI tests
15:37:13         Login
15:37:13           Login works when kube config is missing:
15:37:13       ElementClickInterceptedError: element click intercepted: Element <div class="monaco-list-row focused" role="option" data-index="0" data-last-element="false" data-parity="even" aria-setsize="2" aria-posinset="1" id="list_id_16_0" aria-label="Credentials, Log in to the given server using credentials" aria-level="1" draggable="false" style="top: 0px; height: 22px;">...</div> is not clickable at point (513, 104). Other element would receive the click: <div class="hover-contents" style="white-space: pre-wrap;">...</div>
15:37:13    (Session info: chrome=120.0.6099.291)
15:37:13        at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:521:15)
15:37:13        at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:513:13)
15:37:13        at Executor.execute (node_modules/selenium-webdriver/lib/http.js:446:28)
15:37:13        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
15:37:13        at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:740:17)
15:37:13        at async QuickPickItem.select (node_modules/@redhat-developer/page-objects/out/components/workbench/input/Input.js:245:9)
15:37:13        at async InputBox.selectQuickPick (node_modules/@redhat-developer/page-objects/out/components/workbench/input/Input.js:105:13)
```

### Operating System

Rhel 8

### Visual Studio Code

max

### vscode-extension-tester

8.1.0

### NodeJS

18.15.0

**Comment by kumarmaxwell** [comment]
Hi @lgrossma 
I have noticed this same focus issue in Windows 11 OS recently.. 

@djelinek Could you please clarify whether this issue has something to do with OS. Kindly share your insights or confirmation regarding this.

**Comment by djelinek** [comment]
Hello @kumarmaxwell , afaik this is not OS related thing, it is a flakiness which can happen in some cases where element is taking some time to invoke an action on it but it means focus (cursor) is already on element which can end up in state when hover for that element is show and then the interaction by selenium-webdriver is block because of overlapping hover element
