### ISSUE TITLE
[🚫 Bug] Sporadic StaleElementReferenceError issues

### ISSUE THREAD

**Issue by ronsig** [redhat-developer/vscode-extension-tester#1319]
### Describe the bug

I sometimes get StaleElementReferenceError exceptions on my code, where all it does is reference the driver.
For example, this suite has an outer describe() that does this:

```
 before(async function(){
        testWorkspacePath = await generalHelpers.commonTestSuiteSetup(suiteName);
        await VSBrowser.instance.openResources(testWorkspacePath);
        await (await new ActivityBar().getViewControl(generalHelpers.TestConstants.VIEW_CONTAINER_TITLE))?.openView();
        // now to initialize the view
        const view = new SideBarView();
        content = view.getContent();
    });
    
    and then there's an internal bloc that does this:
     describe('Project View', () => {
        let tree: CustomTreeSection;

        before(async () => {
            //Common.extendProductInfo.setMinimalVersion(24, 4);
            tree = await content.getSection(generalHelpers.TestConstants.STRUCTURE_SECTION_TITLE);
            await generalHelpers.wait(300);
            await tree.expand();

            let driver = POFactory.getDriver(VSBrowser.instance.driver);
            await driver.wait(until.elementLocated(By.css(`div[aria-label="Screens"]`)), 5000, `Timed out on project view`, 100);
        });
```
    
I sometimes get this error:
```
    StaleElementReferenceError: stale element reference: stale element not found
  (Session info: chrome=120.0.6099.291)
    at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:521:15)
    at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:510:13)
    at Executor.execute (node_modules\selenium-webdriver\lib\http.js:443:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (node_modules\selenium-webdriver\lib\webdriver.js:740:17)
```
    
 Is there a way to avoid this issue? Force a refresh?
 
 Thanks!

### Steps to reproduce

```Shell
I don't have specific repro steps. It's a sporadic issue in my tests where the context sometimes goes stale for some reason
```

### Logs

```Shell
StaleElementReferenceError: stale element reference: stale element not found
  (Session info: chrome=120.0.6099.291)
    at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:521:15)
    at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:510:13)
    at Executor.execute (node_modules\selenium-webdriver\lib\http.js:443:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Driver.execute (node_modules\selenium-webdriver\lib\webdriver.js:740:17)
```

### Operating System

Windows 10

### Visual Studio Code

1.88.0

### vscode-extension-tester

8.0.2

### NodeJS

18.13

### npm

8.19.3

**Comment by djelinek** [comment]
Hello, thank you for reporting this. Unfortunately this is a known behaviour which can in some corner cases happen 🙁 . It is a problem of dynamically changing VS Code DOM, which can in some cases cause this issue, mainly because of timing.

So only solution is to identify place where there is this possibility and improve there waiting conditions and mainly try to restore element by another find call..

In past there were some attempts to solve this using state machine approach, if you would be interested in, feel free to take a look on this package - https://github.com/mlorinc/selenium-state-machine


Closing - at the moment there is no plan to work on this issue
