### ISSUE TITLE
[🚫 Bug] HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by sang2770** [redhat-developer/vscode-extension-tester#1353]
### Describe the bug

Downloading ChromeDriver 122.0.6261.128 from: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.128/win64/chromedriver-win64.zip
progress: 0/1449 (0%)
HTTPError: Response code 404 (Not Found)

### Steps to reproduce

```Shell
run "extest get-chromedriver"
```

### Logs

```Shell
Downloading ChromeDriver 122.0.6261.128 from: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.128/win64/chromedriver-win64.zip
progress: 0/1449 (0%)
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (file:///D:/my-extention/test/node_modules/got/dist/source/core/index.js:706:31)
    at Request._onResponse (file:///D:/my-extention/test/node_modules/got/dist/source/core/index.js:768:24)
    at ClientRequest.<anonymous> (file:///D:/my-extention/test/node_modules/got/dist/source/core/index.js:786:23)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
```

### Operating System

Window 10

### Visual Studio Code

1.89.1

### vscode-extension-tester

8.2.0

### NodeJS

20.14.0

### npm

10.7.0

**Comment by djelinek** [comment]
Related to #1340

**Comment by djelinek** [comment]
Fix will be shipped in upcoming release
