### ISSUE TITLE
[🚫 Bug] webview findWebElement() is returning undefined after 8.5.0 release

### ISSUE THREAD

**Issue by alisonlhart** [redhat-developer/vscode-extension-tester#1452]
### Describe the bug

In our extension tests, we are using the WebviewMixinType.findWebElement() method in several tests. After the 8.4.0 release (and in 8.5.0 as well), the return value of that method is coming back either undefined with `TypeError: Cannot read properties of undefined (reading 'findWebElement')` ([example](https://github.com/ansible/vscode-ansible/actions/runs/10160587251/job/28097290030?pr=1462#step:12:435)) 

or with the message ` NoSuchElementError: no such element: Unable to locate element: ...` ([example](https://github.com/ansible/vscode-ansible/actions/runs/10160587251/job/28097290030?pr=1462#step:12:422))

No changes were made outside of upgrading our dependency on ext tester to 8.4.0/8.5.0.

Issue on our extension repo: https://github.com/ansible/vscode-ansible/issues/1464

### Steps to reproduce

```Shell
Source where one of the errors is originating: https://github.com/ansible/vscode-ansible/blob/main/test/ui-test/lightspeedUiTest.ts#L227-L231
```

### Logs

```Shell
1) VSCode Ansible - UI tests
       Verify playbook generation and explanation features work as expected
         Playbook generation webview works as expected (full path) - part 1:
     NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//a[contains(@href,'command:ansible.lightspeed.playbookGeneration')]"}
  (Session info: chrome=122.0.6261.156)
      at Object.throwDecodedError (node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/error.js:521:15)
      at parseHttpResponse (node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/http.js:514:13)
      at Executor.execute (node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/http.js:446:28)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Driver.execute (node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/webdriver.js:742:17)
      at async WebViewBase.findWebElement (node_modules/vscode-extension-tester/node_modules/@redhat-developer/page-objects/out/components/WebviewMixin.js:43:20)
      at async Context.<anonymous> (out/client/test/ui-test/lightspeedUiTest.js:145:41)
```

### Operating System

Fedora 39

### Visual Studio Code

1.91.1

### vscode-extension-tester

8.5.0

### NodeJS

22.4.0

### npm

10.8.1

**Comment by djelinek** [comment]
the problem seems to be related changes made during last upgrade of webdriver @types https://github.com/redhat-developer/vscode-extension-tester/commit/6a943c195b761a58bf7aaa8c1113d996e7b08283

**Comment by alisonlhart** [comment]
This issue is still present after the 8.6.0 release. 
https://github.com/alisonlhart/vscode-ansible/actions/runs/10585584457/job/29332508066?pr=3#step:14:323
