### ISSUE TITLE
[🚫 Bug] Failed to run extest using node 16 

### ISSUE THREAD

**Issue by hellyzh** [redhat-developer/vscode-extension-tester#1476]
### Describe the bug

getting error: 
/usr/local/share/nvm/versions/node/v16.20.2/lib/node_modules/vscode-extension-tester/node_modules/undici/lib/web/fetch/response.js:542
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v16.20.2/lib/node_modules/vscode-extension-tester/node_modules/undici/lib/web/fetch/response.js:542:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v16.20.2/lib/node_modules/vscode-extension-tester/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    screenshot:
![image](https://github.com/user-attachments/assets/e297cc64-dc78-4cc6-9352-2107a0feb1d0)

### Steps to reproduce

```Shell
install node 16
extest get-vscode stable
```

### Logs

```Shell
/usr/local/share/nvm/versions/node/v16.20.2/lib/node_modules/vscode-extension-tester/node_modules/undici/lib/web/fetch/response.js:542
  ReadableStream
  ^

ReferenceError: ReadableStream is not defined
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v16.20.2/lib/node_modules/vscode-extension-tester/node_modules/undici/lib/web/fetch/response.js:542:3)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/usr/local/share/nvm/versions/node/v16.20.2/lib/node_modules/vscode-extension-tester/node_modules/undici/lib/web/fetch/index.js:11:5)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
```

### Operating System

windows and ubuntu

### Visual Studio Code

1.92.0

### vscode-extension-tester

latest

### NodeJS

16.20.2

**Comment by djelinek** [comment]
closing, feel free to reopen or just continue in the thread here in case of more questions.
