### ISSUE TITLE
Selection info from status bar not displayed in all cases

### ISSUE THREAD

**Issue by DuncanWalter** [redhat-developer/vscode-extension-tester#171]
The TextEditor utils provided by the page object API appear to read the current cursor position in documents from the selection info status bar entry. When running tests on narrower screens or with `xvfb-run`, the status bar is often not wide enough for the selection info to be displayed in the status bar. This results in the tests failing. The helper extension for opening folders and files uses a significant chunk of the available status bar space. I also didn't see a way to select the contextMenu opened by right clicking the status bar using the provided utils.

Is there a known workaround for this issue? Maybe there could be a utility for iterating and hiding status bar entries? Or the TextEditor could calculate the current cursor position some other way (a command to the helper extension maybe)?

![image](https://user-images.githubusercontent.com/17483324/95226890-735a8600-07cb-11eb-848c-e84dc43321b5.png)

```
TypeError: coordinates is not iterable
      at TextEditor.<anonymous> (node_modules/monaco-page-objects/out/components/editor/TextEditor.js:247:29)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/editor/TextEditor.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by DuncanWalter** [comment]
Actually, the `getCoordinates()` method may be unneeded. It has one usage outside of this patch:

```diff
diff --git a/node_modules/monaco-page-objects/out/components/editor/TextEditor.js b/node_modules/monaco-page-objects/out/components/editor/TextEditor.js
index 4e10c74..fe59366 100644
--- a/node_modules/monaco-page-objects/out/components/editor/TextEditor.js
+++ b/node_modules/monaco-page-objects/out/components/editor/TextEditor.js
@@ -194,20 +194,18 @@ class TextEditor extends Editor_1.Editor {
                 throw new Error(`Column number ${column} does not exist`);
             }
             const inputarea = yield this.findElement(TextEditor.locators.Editor.inputArea);
-            let coordinates = yield this.getCoordinates();
+            yield inputarea.sendKeys(selenium_webdriver_1.Key.chord(TextEditor.ctlKey, 'a'));
+            yield inputarea.getDriver().actions().sendKeys(selenium_webdriver_1.Key.UP).perform();
+            const coordinates = [1, 1]
             const lineGap = coordinates[0] - line;
             const lineKey = lineGap >= 0 ? selenium_webdriver_1.Key.UP : selenium_webdriver_1.Key.DOWN;
             for (let i = 0; i < Math.abs(lineGap); i++) {
                 yield inputarea.sendKeys(lineKey);
             }
-            coordinates = yield this.getCoordinates();
             const columnGap = coordinates[1] - column;
             const columnKey = columnGap >= 0 ? selenium_webdriver_1.Key.LEFT : selenium_webdriver_1.Key.RIGHT;
             for (let i = 0; i < Math.abs(columnGap); i++) {
                 yield inputarea.sendKeys(columnKey);
-                if ((yield this.getCoordinates())[0] != coordinates[0]) {
-                    throw new Error(`Column number ${column} is not accessible on line ${line}`);
-                }
             }
         });
     }
```

**Comment by jrichter1** [comment]
Good new is that the element is still there, so is the text. I just need to get the text when it is not visible.

**Comment by jrichter1** [comment]
Released new page objects that should contain the fix.
