### ISSUE TITLE
Support VS Code 1.50.0

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#175]
VS Code 1.50.0 ha sbeen released. i tis causing faimures. For instance:

https://travis-ci.org/github/camel-tooling/vscode-camelk/builds/733983141#L788-L805

```
 1) Tooling for Apache Camel K extension
       Extensions view
         "after all" hook for "Verify version":
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".tab-close"}
  (Session info: chrome=83.0.4103.122)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.15.0-1077-gcp x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/travis/build/camel-tooling/vscode-camelk/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .tab-close))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at EditorTab.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at EditorTab.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at EditorGroup.<anonymous> (node_modules/monaco-page-objects/out/components/editor/EditorView.js:210:43)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/editor/EditorView.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

and:
https://travis-ci.org/github/camel-tooling/vscode-wsdl2rest/builds/734218417#L2163-L2200

```
 2) All tests
       Marketplace extension test
         "before all" hook: Init tester and get package data for "Find extension":
     TimeoutError: Waiting until element is visible
Wait timed out after 5002ms
      at /home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at /home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/selenium-webdriver/lib/promise.js:2927:27
      at /home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/selenium-webdriver/lib/promise.js:668:7
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: Waiting until element is visible
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at SideBarView.<anonymous> (node_modules/monaco-page-objects/out/components/AbstractElement.js:50:36)
      at Generator.next (<anonymous>)
      at /home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/monaco-page-objects/out/components/AbstractElement.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/monaco-page-objects/out/components/AbstractElement.js:4:12)
      at SideBarView.wait (node_modules/monaco-page-objects/out/components/AbstractElement.js:49:16)
      at ViewControl.<anonymous> (node_modules/monaco-page-objects/out/components/activityBar/ViewControl.js:36:54)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/activityBar/ViewControl.js:5:58)
  3) All tests
       Marketplace extension test
         "after all" hook: Clear workspace for "Registered all commands":
     TypeError: Cannot read property 'clearSearch' of undefined
      at Context.<anonymous> (out/ui-test/marketplace.test.js:50:31)
      at Generator.next (<anonymous>)
      at /home/travis/build/camel-tooling/vscode-wsdl2rest/out/ui-test/marketplace.test.js:24:71
      at new Promise (<anonymous>)
      at __awaiter (out/ui-test/marketplace.test.js:20:12)
      at Context.<anonymous> (out/ui-test/marketplace.test.js:49:20)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by jrichter1** [comment]
Updated and published

**Comment by apupier** [comment]
there is still the first test that is failing with vscode-extension-tester 3.2.1:
https://travis-ci.org/github/camel-tooling/vscode-camelk/builds/734150795#L764-L781

```
1) Tooling for Apache Camel K extension
       Extensions view
         "after all" hook for "Verify version":
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".tab-close"}
  (Session info: chrome=83.0.4103.122)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 4.15.0-1077-gcp x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/travis/build/camel-tooling/vscode-camelk/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .tab-close))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at EditorTab.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at EditorTab.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at EditorGroup.<anonymous> (node_modules/monaco-page-objects/out/components/editor/EditorView.js:210:43)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/editor/EditorView.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by jrichter1** [comment]
I would suggest regenerating your package-lock.json to get all the dependent packages in latest version.

**Comment by apupier** [comment]
last mentioned error was due to packgae-lock.json which is using 

```
		"vscode-extension-tester-locators": {
			"version": "1.49.0",
			"resolved": "https://registry.npmjs.org/vscode-extension-tester-locators/-/vscode-extension-tester-locators-1.49.0.tgz",
			"integrity": "sha512-I4k0Ph+r9v9x5ocre9mz2uwVNny+g464LP8wD13QxAHdeLjJHgniYKJibOQqhx+7d1y2/5nwlPKwGqH/4fGjuQ==",
			"dev": true
		},
```

instead of

```
		"vscode-extension-tester-locators": {
			"version": "1.50.0",
			"resolved": "https://registry.npmjs.org/vscode-extension-tester-locators/-/vscode-extension-tester-locators-1.50.0.tgz",
			"integrity": "sha512-dxxsQZk9s/zxKIj5aLKqVYqdPMAfQW9rSCGMVuLK6Ac0EDnx2uMe99DthzrfCOiov5BEXdA1MoqCcydrBxxNRg==",
			"dev": true
		},
```

I do no tknow why the 1.49.0 version was picked for VS Code Camel K project and not for Wsdl2rest for instance.

**Comment by apupier** [comment]
> I would suggest regenerating your package-lock.json to get all the dependent packages in latest version.

regenerating the package-lock.json after deleting it was still picking the 1.49.0 version.
