### ISSUE TITLE
How to config for running tests written in typescript?

### ISSUE THREAD

**Issue by freedomhero** [redhat-developer/vscode-extension-tester#182]
I'm trying to run tests written in typescript, so I modified the `.mocharc.json` file to as below:

```
{
  "diff": true,
  "extension": ["ts"],
  "package": "./package.json",
  "reporter": "spec",
  "slow": 75,
  "timeout": 2000,
  "ui": "bdd",
  "require": "ts-node/register"
}
```

Then I run the command: `extest run-tests ui-test/**/*.ts` but nothing happened. It seemed that it did not find the test file which was ui-test/src/demo.test.ts in my case,  the test code was just [from here](https://github.com/redhat-developer/vscode-extension-tester/wiki/Writing-Simple-Tests). So how can I make it work for tests written in typescript?

**Comment by jrichter1** [comment]
I sort of forgot this was an option in mocha. Currently, the only way to run typescript tests is to compile them using `tsc` and then running the generated `.js` files. That being said, I might be able to integrate something like `ts-mocha` to run `.ts` files directly.

**Comment by freedomhero** [comment]
Got it. But when I changed to use js file, I got an error of `TypeError: Cannot read property 'driver' of undefined`, which was just the same as [this issue](https://github.com/redhat-developer/vscode-extension-tester/issues/78), here's some log:

```
$ extest run-tests ui-test/out/*.js

Installing extensions...
(node:94160) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'api-handler.vsix' was successfully installed.
Loading mocha configuration from /Users/hero/work/.mocharc.json


Writing code settings to /Users/hero/work/test-resources/settings/User/settings.json
  My Test Suite
    1) "before all" hook for "My Test Case"

Shutting down the browser
Uninstalling vscode-extension-tester.api-handler...
Extension 'vscode-extension-tester.api-handler' was successfully uninstalled!

  0 passing (5s)
  1 failing

  1) My Test Suite
       "before all" hook for "My Test Case":
     TypeError: Cannot read property 'driver' of undefined
      at /Users/hero/work/ui-test/out/demo.test.js:23:26
      at Generator.next (<anonymous>)
      at /Users/hero/work/ui-test/out/demo.test.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (ui-test/out/demo.test.js:4:12)
      at Context.<anonymous> (ui-test/out/demo.test.js:21:18)
```

The compiled test file `ui-test/out/demo.test.js` was like this:

```
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
const chai = require("chai");
const assert = chai.assert;
// import the webdriver and the high level browser wrapper
const vscode_extension_tester_1 = require("vscode-extension-tester");
// Create a Mocha suite
describe('My Test Suite', () => {
    let browser;
    let driver;
    // initialize the browser and webdriver
    before(() => __awaiter(void 0, void 0, void 0, function* () {
        browser = vscode_extension_tester_1.VSBrowser.instance;
        driver = browser.driver;
    }));
    // test whatever we want using webdriver, here we are just checking the page title
    it('My Test Case', () => __awaiter(void 0, void 0, void 0, function* () {
        const title = yield driver.getTitle();
        assert.isTrue(false);
        assert.equal(title, 'whatever');
    }));
});
//# sourceMappingURL=demo.test.js.map
```

**Comment by jrichter1** [comment]
I've had no luck trying to replicate this. It seems really strange that a part of the API would just stop working, unless the package did somehow not install properly.
At this point I'd just try deleting `node_modules` and `package-lock.json`, then reinstall all the dependencies, recompile and rerun.

**Comment by ssbarnea** [comment]
This issue seems to still be valid and considering that it was closed by the bot, I suspect I might be a mistake.
