### ISSUE TITLE
Not able to debug tests

### ISSUE THREAD

**Issue by andrerim** [redhat-developer/vscode-extension-tester#186]
I'm trying to run the test debugger from the sample project,  but I can't get it to work. I get the following error:

```
C:\testfolder\vscode-extension-tester\sample-projects\helloworld-sample\node_modules\.bin\extest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
So I tried to change the program file to extest.cmd since I'm on windows, but again I get an error:

```
C:\testfolder\vscode-extension-tester\sample-projects\helloworld-sample\node_modules\.bin\extest.cmd:1
@ECHO off
^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Any suggestions as to why this is happening or what I'm doing wrong?

**Comment by jrichter1** [comment]
I'm not quite sure why this is happening. Powershell seems to be perfectly capable of running both executables from its own terminal, yet somehow everything changes when running the launch configuration.

I'm going to look into this a bit more, in the meantime you can try changing the launch config to circumvent the executable, like so:
```
{
		"name": "Debug UI Tests",
		"type": "node",
		"request": "launch",
		"program": "${workspaceFolder}/node_modules/vscode-extension-tester/out/cli.js",
		"args": [
			"setup-and-run",
			"${workspaceFolder}/out/ui-test/*.js",
			"-o",
			"settings.json",
			"--mocha_config",
			"${workspaceFolder}/src/ui-test/.mocharc-debug.js"
		],
		"console": "integratedTerminal",
		"runtimeExecutable": "node",
		"internalConsoleOptions": "neverOpen"
	}
```

**Comment by andrerim** [comment]
Thanks for responding so fast! 

The workaround worked 👍

**Comment by jrichter1** [comment]
I couldn't find the root of the problem, so at least I added the working config to [docs](https://github.com/redhat-developer/vscode-extension-tester/wiki/Debugging-Tests).
