### ISSUE TITLE
WebDriverError when call OutputView clearText

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#189]
1) Test run sCrypt test
       should run sCrypt test successfully:
     WebDriverError: element click intercepted: Element <a class="action-label codicon codicon-clear-all" role="button" title="Clear Output" tabindex="0"></a> is not clickable at point (870, 481). Other element would receive the click: <span>...</span>
  (Session info: chrome=83.0.4103.122)
  (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Windows NT 10.0.17763 x86_64)
      at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
      at D:\a\ide\ide\node_modules\selenium-webdriver\lib\http.js:441:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.click()
      at Driver.schedule (node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at WebElementPromise.schedule_ (node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
      at WebElementPromise.click (node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
      at OutputView.<anonymous> (node_modules\monaco-page-objects\out\components\bottomBar\AbstractViews.js:123:77)
      at Generator.next (<anonymous>)
      at D:\a\ide\ide\node_modules\monaco-page-objects\out\components\bottomBar\AbstractViews.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules\monaco-page-objects\out\components\bottomBar\AbstractViews.js:4:12)
      at OutputView.clearText (node_modules\monaco-page-objects\out\components\bottomBar\AbstractViews.js:121:16)
      at D:\a\ide\ide\ui-test\out\runTest.test.js:71:26

**Comment by jrichter1** [comment]
It says there is another element hovering over the button. My guess is a bunch of notifications could have popped up and intercepted the click. Could you share a screenshot so I can confirm? Failed tests should generate screenshots in `your project root/test-resources/screenshots` by default.

**Comment by zhfnjust** [comment]
i finaly try this, it seems work fine

```

export async function clearsCryptOutput(): Promise<void> {

  await VSBrowser.instance.driver.wait(async () => {

    try {

      await new Workbench().executeCommand('Output: Focus on Output View');
      await new Workbench().executeCommand('View: Clear Output');
      return "success"
    } catch (e) {
      console.log('clearsCryptOutput', e)
    }

  }, 15000, 'getsCryptOutput timeout')

}
