### ISSUE TITLE
Better to check existence of vsce directly not just .bin folder in packageExtension function in codeutil

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-extension-tester#239]
In vscode-knative there was a huge version upgrade in package.json. as a result there is missing vsce under `/node_modules/vscode-extension-tester/node_modules/.bin/`. The check [here] only verifies existence of `.bin` folder, but not `vsce` binary itself. So I would like to introduce check for existence of `vsce` itself.

[here]: https://github.com/redhat-developer/vscode-extension-tester/blob/e1fd51b615386677e2b3b8f254fe80b9502875c6/src/util/codeUtil.ts#L197

**Comment by odockal** [comment]
Apparently, js-yaml package when upgraded to 4.x version brings its binary and is responsible for creating node_modules/.bin/js-yaml binary. And so there is this `.bin` folder without vsce that leads to the error.

Error is like:
```
Downloading VS Code from: https://vscode-update.azurewebsites.net/latest/linux-x64/stable
Downloaded VS Code into /home/runner/work/vscode-knative/vscode-knative/test-resources/stable.tar.gz
Unpacking VS Code into /home/runner/work/vscode-knative/vscode-knative/test-resources
Success!
Downloading ChromeDriver 87.0.4280.88 from: https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip
Unpacking ChromeDriver 87.0.4280.88 into /home/runner/work/vscode-knative/vscode-knative/test-resources
Success!
/bin/sh: 1: /home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/node_modules/.bin/vsce: not found
Error: Command failed: /home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at CodeUtil.packageExtension (/home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/out/util/codeUtil.js:173:23)
    at ExTester.<anonymous> (/home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/out/extester.js:73:27)
    at Generator.next (<anonymous>)
    at /home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/out/extester.js:54:16)
    at ExTester.<anonymous> (/home/runner/work/vscode-knative/vscode-knative/node_modules/vscode-extension-tester/out/extester.js:108:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-knative@0.9.2 base-ui-test: `npm run compile && extest setup-and-run out/test/ui-test/baseTestsSuite.js -e ~/notTestFolder -i`
npm ERR! Exit status 1
```
