### ISSUE TITLE
clicking a context menu item sometimes results in a NoSuchSessionError

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#247]
I have been unsuccessfully trying to find the cause of my test suite dying with `NoSuchSessionError`. I am trying to click an entry in the menu of a tree element of a custom tree, but the test is randomly falling with a stack trace like the following one:
```
/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/mocha/lib/runner.js:962
    throw err;
    ^

NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
    at /home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:847:16
    at new ManagedPromise (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:1077:7)
    at ControlFlow.promise (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:2505:12)
    at /home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:846:34
    at /home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:1684:12
    at ManagedPromise.invokeCallback_ (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at /home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:2927:27
    at /home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/promise.js:668:7
From: Task: WebDriver.findElement(By(css selector, html))
    at Driver.schedule (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at Driver.findElement (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:1014:17)
    at new AbstractElement (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/monaco-page-objects/out/components/AbstractElement.js:25:43)
    at new Workbench (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/monaco-page-objects/out/components/workbench/Workbench.js:30:9)
    at Object.<anonymous> (/home/dan/suse/github.com/SUSE/open-build-service-connector/out/ui-tests/util.js:135:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/dan/suse/github.com/SUSE/open-build-service-connector/out/ui-tests/util.js:26:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebElement.findElement(By(css selector, .monaco-workbench))
    at Driver.schedule (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElementPromise.schedule_ (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at WebElementPromise.findElement (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
    at new AbstractElement (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
    at new Workbench (/home/dan/suse/github.com/SUSE/open-build-service-connector/node_modules/monaco-page-objects/out/components/workbench/Workbench.js:30:9)
    at Object.<anonymous> (/home/dan/suse/github.com/SUSE/open-build-service-connector/out/ui-tests/util.js:135:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/dan/suse/github.com/SUSE/open-build-service-connector/out/ui-tests/util.js:26:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  remoteStacktrace: ''
}
error Command failed with exit code 7.
```

and the test code looks like this:
```typescript
    it("opens the settings.json and puts the cursor to the correct position", async () => {
      // this is a tree element
      const acc1Element = await waitForObsInstance(testAccount.apiUrl);

      const openSettingsElement = await (
        await acc1Element.openContextMenu()
      ).getItem("Open the settings of a account in the Open Build Service");
      expect(openSettingsElement).to.not.equal(undefined);
      await openSettingsElement!.select();

      const editorView = await new EditorView().wait();
      // this just retries the passed function a few times until it no longer throws or does not return undefined
      await waitForElement(
        async () => await editorView.openEditor(SETTINGS_JSON)
      );
      const settingsJsonEditor = new TextEditor();

      const [line, col] = await settingsJsonEditor.getCoordinates();
      const lineAtCursor = await settingsJsonEditor.getTextAtLine(line);
      lineAtCursor
        .slice(col)
        .should.equal(`"apiUrl": "${testAccount.apiUrl}",`);
    });
```

Looking at the screenshot, I see that the correct menu item is actually selected, it's just that nothing happens afterwards. VSCode simply stops and the test fails.

Unfortunately, I have everything but a reproducer: this test just fails randomly. It appears to succeed far more frequently, if all tests before it are skipped and it fails more frequently if the system is under load.

Could it be that webdriver is somehow not actually clicking the menu entry? I have inserted the following lines after the `select()` and that has not yet failed so far (sometimes it gets into the if branch and sometimes it doesn't):
```typescript
      // after await openSettingsElement!.select();
      try {
        if (!(await openSettingsElement!.isSelected())) {
          await openSettingsElement!.select();
        }
      } catch {}
```

Any ideas what could be going on here?

**Comment by jrichter1** [comment]
I have a theory, not sure if it's correct though...

VS Code displays the context menu before it actually loads all its items. Every time a new item get loaded, the menu is briefly disabled and redrawn. And since extester only waits for the context menu to be displayed, it might be clicking on an element right as the menu is reloading. 

It could be that just waiting for the menu to fully load is enough. Could you try inserting a sleep right between opening the context menu and searching for the menu item? A second's worth should be plenty enough.

**Comment by jrichter1** [comment]
Is this still happening with 4.0.1 ?
