### ISSUE TITLE
Test broken on master with VS code 1.51.0 and 1.53.0 Simple open file dialog -> Opens a file

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#266]
```
  1) Simple open file dialog
       Opens a file:
     Error: No editor with title 'package.json' available
      at EditorGroup.<anonymous> (/home/runner/work/vscode-extension-tester/vscode-extension-tester/page-objects/out/components/editor/EditorView.js:266:23)
      at Generator.next (<anonymous>)
      at fulfilled (/home/runner/work/vscode-extension-tester/vscode-extension-tester/page-objects/out/components/editor/EditorView.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

see https://github.com/redhat-developer/vscode-extension-tester/runs/2279057196?check_suite_focus=true#step:5:429 and https://github.com/redhat-developer/vscode-extension-tester/runs/2279057111?check_suite_focus=true#step:5:429

**Comment by jrichter1** [comment]
Simple open dialog no longer misbehaving
