### ISSUE TITLE
extest get-chromedriver and get-vscode fails when connected to proxy

### ISSUE THREAD

**Issue by alii-gator** [redhat-developer/vscode-extension-tester#268]
Is there a recommended way to make it work when we are behind a proxy?
I have tried setting proxy in vscode settings but it fails with the following error.

``` 
extest get-vscode && extest get-chromedriver && npm run get-extension && npm run extraction
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at C:\Users\SBALI\Documents\sdf\gitlab\vscode-integration-tests\node_modules\vscode-extension-tester\out\util\codeUtil.js:75:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vscode-e2e-tests@1.0.0 setup-env: `extest get-vscode && extest get-chromedriver && npm run get-extension && npm run extraction`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vscode-e2e-tests@1.0.0 setup-env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\abc\AppData\Roaming\npm-cache\_logs\2021-04-20T13_54_58_898Z-debug.log```

**Comment by alii-gator** [comment]
Never mind I found a solution.

Keep up the good work.
