### ISSUE TITLE
Debug session does not work `SyntaxError: missing ) after argument list`

### ISSUE THREAD

**Issue by microhobby** [redhat-developer/vscode-extension-tester#269]
I'm trying to use the hello world sample I'm getting this return (running from VS Code pressing F5 selecting the `Debug UI Test`):

```
${env:NODE_OPTIONS}='--require "c:/Users/mpro3/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" --inspect-publish-uid=http'; ${env:VSCODE_INSPECTOR_OPTIONS}='{"inspectorIpc":"\\\\.\\pipe\\node-cdp.6820-25.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\Program Files\\nodejs\\node.exe","onlyEntrypoint":false,"autoAttachMode":"always","fileCallback":"C:\\Users\\mpro3\\AppData\\Local\\Temp\\node-debug-callback-ea17476a4b4a08e1"}'; & 'C:\Program Files\nodejs\node.exe' '.\node_modules\.bin\extest' 'setup-and-run' 'D:\Projects\X\uno-extension\uno-platform/out/ui-test/*.js' '-o' 'settings.json' '--mocha_config' 'D:\Projects\X\uno-extension\uno-platform/src/ui-test/.mocharc-debug.js' 
Debugger attached.
Waiting for the debugger to disconnect...
D:\Projects\X\uno-extension\uno-platform\node_modules\.bin\extest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

This is my `devDependencies`:

```
	"devDependencies": {
		"@types/chai": "^4.1.7",
		"@types/node": "^14.0.0",
		"@types/vscode": "^1.34.0",
		"@types/mocha": "7.0.2",
		"chai": "^4.2.0",
		"mocha": "^6.2.0",
		"tslint": "^5.16.0",
		"typescript": "4.0.3",
		"vscode-extension-tester": "^4.0.2"
	}
```

I had to update `vscode-extension-tester` and add the `@types/mocha` to the `devDependencies`.

**Comment by microhobby** [comment]
Important to say that I am on Windows:

```
Version: 1.56.0-insider (user setup)
Commit: b4816cfd1f4161a3bb272354d181a9947760ee26
Date: 2021-04-20T07:23:51.425Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.21359
```

**Comment by jrichter1** [comment]
This looks like there is a problem with the executable, but I'm assuming calling `extest` in your npm scripts still works, which would make it all the more confusing.

Could you try editing the debug configuration to point to the original js file, instead of the .bin one? The line should look like this:
`"program": "${workspaceFolder}/node_modules/vscode-extension-tester/out/cli.js"`

**Comment by microhobby** [comment]
@jrichter1 thanks, changing the program to `cli.js` works!
And yes, if I call the script:

```
"ui-test": "npm run compile && extest setup-and-run out/ui-test/*.js -o settings.json"
```

The `extest` appears to work, the problem is only with the debug session.
