### ISSUE TITLE
call click on ViewPanelAction throws 

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#272]
![image](https://user-images.githubusercontent.com/995909/116258743-ca479d00-a7a7-11eb-845e-b823369a7a09.png)

```javascript

		const Refresh = await sections[0].getAction("Refresh");

		Refresh.click()

```

 Uncaught ElementNotVisibleError: element not interactable
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}),platform=Windows NT 10.0.19042 x86_64)
      at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:546:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
      at C:\Users\myland\code\ide2\node_modules\selenium-webdriver\lib\http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: WebElement.click()
      at Driver.schedule (node_modules\selenium-webdriver\lib\webdriver.js:807:17)
      at ViewPanelAction.schedule_ (node_modules\selenium-webdriver\lib\webdriver.js:2010:25)
      at ViewPanelAction.click (node_modules\selenium-webdriver\lib\webdriver.js:2092:17)
      at Suite.<anonymous> (ui-test\out\deploy-compile.test.js:73:17)
      at Generator.next (<anonymous>)
      at fulfilled (ui-test\out\deploy-compile.test.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by zhfnjust** [comment]
Finally solove, i should click the section title before click the `refresh` button

```javascript

		await sections[0].click();
		const Refresh = await sections[0].getAction("Refresh");

		Refresh.click()

```
