### ISSUE TITLE
not able to access EditorView right after WebView.switchback()

### ISSUE THREAD

**Issue by immanishbainsla** [redhat-developer/vscode-extension-tester#281]
error : Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-workbench"}
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}),platform=Linux 5.10.15-200.fc33.x86_64 x86_64)

have tried this as well 
``
const browser = VSBrowser.instance;
await browser.waitForWorkbench();
``

cc : @jrichter1 

ps : I want to access editorView to close some tabs opened in editor

**Comment by immanishbainsla** [comment]
complete error : 
at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/user/.../node_modules/selenium-webdriver/lib/http.js:441:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-workbench))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElementPromise.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElementPromise.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
      at new Workbench (node_modules/monaco-page-objects/out/components/workbench/Workbench.js:30:9)
      at Context.<anonymous> (out/ui-test/manifestFileTests/pypiWithVulns.js:179:35)
      at Generator.next (<anonymous>)
      at /home/user/.../out/ui-test/manifestFileTests/pypiWithVulns.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (out/ui-test/manifestFileTests/pypiWithVulns.js:4:12)

**Comment by jrichter1** [comment]
Not much to go on here without looking at the code. [Unit tests](https://github.com/redhat-developer/vscode-extension-tester/blob/master/test/test-project/src/test/editor/webView-test.ts) run smoothly, while using this very function.
