### ISSUE TITLE
helloworld-sample: WebDriverError: element not interactable

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#29]
Hi, I am having trouble running the sample project's tests

After following the instructions in the sample project's readme, I ran `npm run ui-test` and I have a test failure:

```
 1) Hello World Command should show a notification with the correct text

Waiting for all webdriver tasks to finish
Shutting down the browser

  0 passing (6s)
  1 failing

  1) Hello World Example UI Tests
       Hello World Command should show a notification with the correct text:
     WebDriverError: element not interactable
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.0.17-300.fc30.x86_64 x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/dakwon/git/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
  From: Task: WebElement.sendKeys()
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.sendKeys (node_modules/selenium-webdriver/lib/webdriver.js:2174:19)
      at QuickOpenBox.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:39:25)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

The error seems to happen on this line: https://github.com/redhat-developer/vscode-extension-tester/blob/619fbae04b6c65ca56cfc47c4b549fede8e3991b/sample-projects/helloworld-sample/src/ui-test/hello-world-test.ts#L21

Maybe I am doing something wrong?

**Comment by xorye** [comment]
This only seems to happen when I am using the specify the latest version of VS Code and the latest version of ChromeDriver.

If provide the `-c 1.34.0` flag to the `extest setup-and-run` command, I don't get this issue

**Comment by jrichter1** [comment]
I'm back, sorry for the delay.

This is definitely a misconfiguration in the sample project. I think it is trying to pull an older version of extension tester, so it has some trouble with the new VS Code. I'll fix that momentarily, meanwhile you can try navigating into the helloworld-sample folder and run
```
npm update vscode-extension-tester
```
That should force it to update to 2.1.0

**Comment by jrichter1** [comment]
I've updated the dependencies and some configuration of the project, it should now use the correct version of the framework. I've also removed the sample project's package-lock file so this hopefully won't happen every new release.

**Comment by xorye** [comment]
great, thank you!
