### ISSUE TITLE
switchToFrame fail

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#292]
```

  1) deploy.test
       compile and deploy demo:
     NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"iframe[class='webview ready']"}
  (Session info: chrome=87.0.4280.141)
  (Driver info: chromedriver=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}),platform=Linux 5.4.0-74-generic x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/hh/code/ide/node_modules/selenium-webdriver/lib/http.js:441:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: WebDriver.findElement(By(css selector, iframe[class='webview ready']))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:1014:17)
      at WebView.<anonymous> (node_modules/monaco-page-objects/out/components/editor/WebView.js:56:53)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/editor/WebView.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)




```

**Comment by domhanak** [comment]
Hello, I encountered this issue too. 

I do not have a proper fix but what helped was adding couple of waits for `webview ready` iframe and `active-frame` iframe before I let my tests use `switchToFrame`

You can check it here https://github.com/kiegroup/kogito-tooling/blob/2174d9430f25056008466ec65ce6fa118246ad46/packages/vscode-extension-pack-kogito-kie-editors/it-tests/helpers/VSCodeTestHelper.ts#L187 it is not nice but work for now.

**Comment by jrichter1** [comment]
Looks like a case of more complex webviews needing more time to load. I can add some wait, pretty much as @domhanak has, to give it more time.

**Comment by zhfnjust** [comment]
when update my tested vscode version  to latest ,i work fine, 

but error still occurs on version  1.55.2

**Comment by zhfnjust** [comment]
finaly, i found this error is cause by the `monaco-page-objects` which version is `1.5.2`, 

now i lock below and work fine

```
 vscode: 1.55.2

"vscode-extension-tester": "4.0.2",
"monaco-page-objects": "1.5.2",
```
