### ISSUE TITLE
Cannot launch VS Code App in Mac

### ISSUE THREAD

**Issue by lakxraju** [redhat-developer/vscode-extension-tester#30]
First of all, thanks for developing this helper. 

I am trying to integrate vscode-extension-tester into my application (in Mac). Here is the error while installing the my vsix file into the VSCode app. 

_Installing <extension>.vsix 
/bin/sh: /tmp/.vscode_selenium_temp/Visual: No such file or directory
(node:70604) UnhandledPromiseRejectionWarning: Error: Command failed: ELECTRON_RUN_AS_NODE=1 /tmp/.vscode_selenium_temp/Visual Studio Code.app/Contents/MacOS/Electron /tmp/.vscode_selenium_temp/Visual Studio Code.app/Contents/Resources/app/out/cli.js --install-extension <my-extension>.vsix
    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at CodeUtil.installExtension (/vscode_extension/node_modules/vscode-extension-tester/out/util/codeUtil.js:113:23)
    at ExTester.installVsix (/vscode_extension/node_modules/vscode-extension-tester/out/extester.js:88:26)
    at ExTester.<anonymous> (/vscode_extension/node_modules/vscode-extension-tester/out/extester.js:115:18)
    at Generator.next (<anonymous>)
    at fulfilled (/vscode_extension/node_modules/vscode-extension-tester/out/extester.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:70604) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)_

**Comment by jrichter1** [comment]
Hi, thanks for trying out the framework!

The problem looks like unwanted string interpolation, namely the spaces in the path. I'm going to dig into this ASAP.

**Comment by lakxraju** [comment]
Fixed the issue locally by changing the command formation into: (in installExtension() method)

const command = [this.cliEnv, `"${this.executablePath}"`, `"${this.cliPath}"`, `--install-extension "${vsixPath}"`].join(' ');

**Comment by lakxraju** [comment]
Hi @jrichter1 , Is it possible to initiate a minor npm release ?

**Comment by jrichter1** [comment]
2.1.1 should be out now, enjoy :)
