### ISSUE TITLE
Error: Command failed: /Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/node_modules/.bin/vsce package --no-yarn

### ISSUE THREAD

**Issue by AllanOricil** [redhat-developer/vscode-extension-tester#307]
It downloads the wrong chrome webdriver. Im using Chrome 90. And Im also getting this error.
Im on Mac Mini M1

````
$ extest setup-and-run -s ./test -e ./test/extensions -c 1.57.0 -t stable ./test/query-editor.js -l DEBUG
Downloading VS Code from: https://update.code.visualstudio.com/1.57.0/darwin/stable
Downloaded VS Code into /Users/allanoricil/salesforce-query-editor/test/stable.zip
Unpacking VS Code into /Users/allanoricil/salesforce-query-editor/test
Success!
Downloading ChromeDriver 89.0.4389.23 from: https://chromedriver.storage.googleapis.com/89.0.4389.23/chromedriver_mac64.zip
Unpacking ChromeDriver 89.0.4389.23 into /Users/allanoricil/salesforce-query-editor/test
Success!
 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
npm ERR! missing: applicationinsights@1.8.2, required by salesforce-soql-editor@1.8.0
npm ERR! missing: axios@0.21.1, required by salesforce-soql-editor@1.8.0
npm ERR! missing: cors@2.8.5, required by salesforce-soql-editor@1.8.0
npm ERR! missing: dateformat@4.5.1, required by salesforce-soql-editor@1.8.0
npm ERR! missing: dotenv@8.2.0, required by salesforce-soql-editor@1.8.0
npm ERR! missing: express@4.17.1, required by salesforce-soql-editor@1.8.0
npm ERR! missing: fs-extra@9.0.1, required by salesforce-soql-editor@1.8.0
npm ERR! missing: morgan-body@2.6.4, required by salesforce-soql-editor@1.8.0
npm ERR! missing: node-machine-id@1.1.12, required by salesforce-soql-editor@1.8.0
npm ERR! missing: objects-to-csv@1.3.6, required by salesforce-soql-editor@1.8.0
npm ERR! missing: open@8.0.2, required by salesforce-soql-editor@1.8.0
npm ERR! missing: qs@6.9.4, required by salesforce-soql-editor@1.8.0
npm ERR! missing: rotating-file-stream@2.1.3, required by salesforce-soql-editor@1.8.0
npm ERR! missing: socket.io@2.4.1, required by salesforce-soql-editor@1.8.0
npm ERR! missing: @types/vscode@^1.56.0, required by salesforce-soql-editor@1.8.0
npm ERR! missing: mocha@^9.0.1, required by salesforce-soql-editor@1.8.0
npm ERR! missing: cls-hooked@4.2.2, required by applicationinsights@1.8.2
npm ERR! missing: continuation-local-storage@3.2.1, required by applicationinsights@1.8.2
npm ERR! missing: diagnostic-channel@0.3.1, required by applicationinsights@1.8.2
npm ERR! missing: diagnostic-channel-publishers@0.4.0, required by applicationinsights@1.8.2
npm ERR! missing: async-hook-jl@1.7.6, required by cls-hooked@4.2.2
npm ERR! missing: emitter-listener@1.1.2, required by cls-hooked@4.2.2
npm ERR! missing: semver@5.7.1, required by cls-hooked@4.2.2
npm ERR! missing: stack-chain@1.3.7, required by async-hook-jl@1.7.6
npm ERR! missing: shimmer@1.2.1, required by emitter-listener@1.1.2
npm ERR! missing: async-listener@0.6.10, required by continuation-local-storage@3.2.1
npm ERR! missing: emitter-listener@1.1.2, required by continuation-local-storage@3.2.1
npm ERR! missing: semver@5.7.1, required by async-listener@0.6.10
npm ERR! missing: shimmer@1.2.1, required by async-listener@0.6.10
npm ERR! missing: semver@5.7.1, required by diagnostic-channel@0.3.1
npm ERR! missing: follow-redirects@1.13.1, required by axios@0.21.1
npm ERR! missing: object-assign@4.1.1, required by cors@2.8.5
npm ERR! missing: vary@1.1.2, required by cors@2.8.5
npm ERR! missing: accepts@1.3.7, required by express@4.17.1
npm ERR! missing: array-flatten@1.1.1, required by express@4.17.1
npm ERR! missing: body-parser@1.19.0, required by express@4.17.1
npm ERR! missing: content-disposition@0.5.3, required by express@4.17.1
npm ERR! missing: content-type@1.0.4, required by express@4.17.1
npm ERR! missing: cookie@0.4.0, required by express@4.17.1
npm ERR! missing: cookie-signature@1.0.6, required by express@4.17.1
npm ERR! missing: depd@1.1.2, required by express@4.17.1
npm ERR! missing: encodeurl@1.0.2, required by express@4.17.1
npm ERR! missing: escape-html@1.0.3, required by express@4.17.1
npm ERR! missing: etag@1.8.1, required by express@4.17.1
npm ERR! missing: debug@2.6.9, required by express@4.17.1
npm ERR! missing: qs@6.7.0, required by express@4.17.1
npm ERR! missing: finalhandler@1.1.2, required by express@4.17.1
npm ERR! missing: fresh@0.5.2, required by express@4.17.1
npm ERR! missing: merge-descriptors@1.0.1, required by express@4.17.1
npm ERR! missing: methods@1.1.2, required by express@4.17.1
npm ERR! missing: on-finished@2.3.0, required by express@4.17.1
npm ERR! missing: parseurl@1.3.3, required by express@4.17.1
npm ERR! missing: path-to-regexp@0.1.7, required by express@4.17.1
npm ERR! missing: proxy-addr@2.0.6, required by express@4.17.1
npm ERR! missing: range-parser@1.2.1, required by express@4.17.1
npm ERR! missing: safe-buffer@5.1.2, required by express@4.17.1
npm ERR! missing: send@0.17.1, required by express@4.17.1
npm ERR! missing: serve-static@1.14.1, required by express@4.17.1
npm ERR! missing: setprototypeof@1.1.1, required by express@4.17.1
npm ERR! missing: statuses@1.5.0, required by express@4.17.1
npm ERR! missing: type-is@1.6.18, required by express@4.17.1
npm ERR! missing: utils-merge@1.0.1, required by express@4.17.1
npm ERR! missing: vary@1.1.2, required by express@4.17.1
npm ERR! missing: mime-types@2.1.28, required by accepts@1.3.7
npm ERR! missing: negotiator@0.6.2, required by accepts@1.3.7
npm ERR! missing: mime-db@1.45.0, required by mime-types@2.1.28
npm ERR! missing: debug@2.6.9, required by body-parser@1.19.0
npm ERR! missing: qs@6.7.0, required by body-parser@1.19.0
npm ERR! missing: bytes@3.1.0, required by body-parser@1.19.0
npm ERR! missing: content-type@1.0.4, required by body-parser@1.19.0
npm ERR! missing: depd@1.1.2, required by body-parser@1.19.0
npm ERR! missing: http-errors@1.7.2, required by body-parser@1.19.0
npm ERR! missing: iconv-lite@0.4.24, required by body-parser@1.19.0
npm ERR! missing: on-finished@2.3.0, required by body-parser@1.19.0
npm ERR! missing: raw-body@2.4.0, required by body-parser@1.19.0
npm ERR! missing: type-is@1.6.18, required by body-parser@1.19.0
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: depd@1.1.2, required by http-errors@1.7.2
npm ERR! missing: inherits@2.0.3, required by http-errors@1.7.2
npm ERR! missing: setprototypeof@1.1.1, required by http-errors@1.7.2
npm ERR! missing: statuses@1.5.0, required by http-errors@1.7.2
npm ERR! missing: toidentifier@1.0.0, required by http-errors@1.7.2
npm ERR! missing: safer-buffer@2.1.2, required by iconv-lite@0.4.24
npm ERR! missing: bytes@3.1.0, required by raw-body@2.4.0
npm ERR! missing: http-errors@1.7.2, required by raw-body@2.4.0
npm ERR! missing: iconv-lite@0.4.24, required by raw-body@2.4.0
npm ERR! missing: unpipe@1.0.0, required by raw-body@2.4.0
npm ERR! missing: safe-buffer@5.1.2, required by content-disposition@0.5.3
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: encodeurl@1.0.2, required by finalhandler@1.1.2
npm ERR! missing: escape-html@1.0.3, required by finalhandler@1.1.2
npm ERR! missing: debug@2.6.9, required by finalhandler@1.1.2
npm ERR! missing: on-finished@2.3.0, required by finalhandler@1.1.2
npm ERR! missing: parseurl@1.3.3, required by finalhandler@1.1.2
npm ERR! missing: statuses@1.5.0, required by finalhandler@1.1.2
npm ERR! missing: unpipe@1.0.0, required by finalhandler@1.1.2
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: ee-first@1.1.1, required by on-finished@2.3.0
npm ERR! missing: forwarded@0.1.2, required by proxy-addr@2.0.6
npm ERR! missing: ipaddr.js@1.9.1, required by proxy-addr@2.0.6
npm ERR! missing: depd@1.1.2, required by send@0.17.1
npm ERR! missing: destroy@1.0.4, required by send@0.17.1
npm ERR! missing: encodeurl@1.0.2, required by send@0.17.1
npm ERR! missing: escape-html@1.0.3, required by send@0.17.1
npm ERR! missing: etag@1.8.1, required by send@0.17.1
npm ERR! missing: fresh@0.5.2, required by send@0.17.1
npm ERR! missing: http-errors@1.7.2, required by send@0.17.1
npm ERR! missing: mime@1.6.0, required by send@0.17.1
npm ERR! missing: on-finished@2.3.0, required by send@0.17.1
npm ERR! missing: range-parser@1.2.1, required by send@0.17.1
npm ERR! missing: debug@2.6.9, required by send@0.17.1
npm ERR! missing: ms@2.1.1, required by send@0.17.1
npm ERR! missing: statuses@1.5.0, required by send@0.17.1
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: encodeurl@1.0.2, required by serve-static@1.14.1
npm ERR! missing: escape-html@1.0.3, required by serve-static@1.14.1
npm ERR! missing: parseurl@1.3.3, required by serve-static@1.14.1
npm ERR! missing: send@0.17.1, required by serve-static@1.14.1
npm ERR! missing: media-typer@0.3.0, required by type-is@1.6.18
npm ERR! missing: mime-types@2.1.28, required by type-is@1.6.18
npm ERR! missing: at-least-node@1.0.0, required by fs-extra@9.0.1
npm ERR! missing: graceful-fs@4.2.4, required by fs-extra@9.0.1
npm ERR! missing: jsonfile@6.0.1, required by fs-extra@9.0.1
npm ERR! missing: universalify@1.0.0, required by fs-extra@9.0.1
npm ERR! missing: graceful-fs@4.2.4, required by jsonfile@6.0.1
npm ERR! missing: universalify@1.0.0, required by jsonfile@6.0.1
npm ERR! missing: moment-timezone@0.5.32, required by morgan-body@2.6.4
npm ERR! missing: on-finished@2.3.0, required by morgan-body@2.6.4
npm ERR! missing: on-headers@1.0.2, required by morgan-body@2.6.4
npm ERR! missing: moment@2.29.1, required by moment-timezone@0.5.32
npm ERR! missing: async-csv@2.1.3, required by objects-to-csv@1.3.6
npm ERR! missing: csv@5.3.2, required by async-csv@2.1.3
npm ERR! missing: csv-generate@3.2.4, required by csv@5.3.2
npm ERR! missing: csv-parse@4.12.0, required by csv@5.3.2
npm ERR! missing: csv-stringify@5.5.1, required by csv@5.3.2
npm ERR! missing: stream-transform@2.0.2, required by csv@5.3.2
npm ERR! missing: mixme@0.3.5, required by stream-transform@2.0.2
npm ERR! missing: define-lazy-prop@2.0.0, required by open@8.0.2
npm ERR! missing: is-docker@2.1.1, required by open@8.0.2
npm ERR! missing: is-wsl@2.2.0, required by open@8.0.2
npm ERR! missing: is-docker@2.1.1, required by is-wsl@2.2.0
npm ERR! missing: debug@4.1.1, required by socket.io@2.4.1
npm ERR! missing: engine.io@3.5.0, required by socket.io@2.4.1
npm ERR! missing: has-binary2@1.0.3, required by socket.io@2.4.1
npm ERR! missing: socket.io-adapter@1.1.2, required by socket.io@2.4.1
npm ERR! missing: socket.io-client@2.4.0, required by socket.io@2.4.1
npm ERR! missing: socket.io-parser@3.4.1, required by socket.io@2.4.1
npm ERR! missing: ms@2.1.2, required by debug@4.1.1
npm ERR! missing: accepts@1.3.7, required by engine.io@3.5.0
npm ERR! missing: base64id@2.0.0, required by engine.io@3.5.0
npm ERR! missing: debug@4.1.1, required by engine.io@3.5.0
npm ERR! missing: engine.io-parser@2.2.1, required by engine.io@3.5.0
npm ERR! missing: cookie@0.4.1, required by engine.io@3.5.0
npm ERR! missing: ws@7.4.2, required by engine.io@3.5.0
npm ERR! missing: after@0.8.2, required by engine.io-parser@2.2.1
npm ERR! missing: arraybuffer.slice@0.0.7, required by engine.io-parser@2.2.1
npm ERR! missing: base64-arraybuffer@0.1.4, required by engine.io-parser@2.2.1
npm ERR! missing: blob@0.0.5, required by engine.io-parser@2.2.1
npm ERR! missing: has-binary2@1.0.3, required by engine.io-parser@2.2.1
npm ERR! missing: isarray@2.0.1, required by has-binary2@1.0.3
npm ERR! missing: backo2@1.0.2, required by socket.io-client@2.4.0
npm ERR! missing: component-bind@1.0.0, required by socket.io-client@2.4.0
npm ERR! missing: component-emitter@1.3.0, required by socket.io-client@2.4.0
npm ERR! missing: engine.io-client@3.5.0, required by socket.io-client@2.4.0
npm ERR! missing: has-binary2@1.0.3, required by socket.io-client@2.4.0
npm ERR! missing: indexof@0.0.1, required by socket.io-client@2.4.0
npm ERR! missing: parseqs@0.0.6, required by socket.io-client@2.4.0
npm ERR! missing: parseuri@0.0.6, required by socket.io-client@2.4.0
npm ERR! missing: debug@3.1.0, required by socket.io-client@2.4.0
npm ERR! missing: socket.io-parser@3.3.2, required by socket.io-client@2.4.0
npm ERR! missing: to-array@0.1.4, required by socket.io-client@2.4.0
npm ERR! missing: component-emitter@1.3.0, required by engine.io-client@3.5.0
npm ERR! missing: component-inherit@0.0.3, required by engine.io-client@3.5.0
npm ERR! missing: debug@3.1.0, required by engine.io-client@3.5.0
npm ERR! missing: engine.io-parser@2.2.1, required by engine.io-client@3.5.0
npm ERR! missing: has-cors@1.1.0, required by engine.io-client@3.5.0
npm ERR! missing: indexof@0.0.1, required by engine.io-client@3.5.0
npm ERR! missing: parseqs@0.0.6, required by engine.io-client@3.5.0
npm ERR! missing: parseuri@0.0.6, required by engine.io-client@3.5.0
npm ERR! missing: ws@7.4.2, required by engine.io-client@3.5.0
npm ERR! missing: xmlhttprequest-ssl@1.5.5, required by engine.io-client@3.5.0
npm ERR! missing: yeast@0.1.2, required by engine.io-client@3.5.0
npm ERR! missing: ms@2.0.0, required by debug@3.1.0
npm ERR! missing: ms@2.0.0, required by debug@3.1.0
npm ERR! missing: component-emitter@1.3.0, required by socket.io-parser@3.3.2
npm ERR! missing: debug@3.1.0, required by socket.io-parser@3.3.2
npm ERR! missing: isarray@2.0.1, required by socket.io-parser@3.3.2
npm ERR! missing: debug@4.1.1, required by socket.io-parser@3.4.1
npm ERR! missing: component-emitter@1.2.1, required by socket.io-parser@3.4.1
npm ERR! missing: isarray@2.0.1, required by socket.io-parser@3.4.1

Error: Command failed: /Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at CodeUtil.packageExtension (/Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/out/util/codeUtil.js:181:23)
    at ExTester.<anonymous> (/Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/out/extester.js:58:16)
    at ExTester.<anonymous> (/Users/allanoricil/salesforce-query-editor/node_modules/vscode-extension-tester/out/extester.js:123:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
allanoricil@Allans-Mac-mini salesforce-query-editor % 
````

**Comment by AllanOricil** [comment]
This issue was caused because I forgot to pass the "-y" flag
