### ISSUE TITLE
Error: Value not available in settings editor.

### ISSUE THREAD

**Issue by afrinj** [redhat-developer/vscode-extension-tester#328]
Scenario:

What i am trying is to change the **json** value from settings editor.

Source : link
https://github.com/redhat-developer/vscode-extension-tester/blob/master/test/test-project/src/test/editor/settingsEditor-test.ts

Added modified code:

```
    describe('Link setting', () => {
        let setting: LinkSetting;
        before(async function() {
            this.timeout(15000);
            setting = await editor.findSetting('Code Actions On Save','Editor') as LinkSetting;
        });

        it('setValue works', async () => {
            //await setting.openLink();
            await setting.setValue("null");
        });
```
Gives below error:

    ```
     Error: Value not available in settings editor.
     
     at LinkSetting.<anonymous> (node_modules/monaco-page-objects/out/components/editor/SettingsEditor.js:278:19)
      at Generator.next (<anonymous>)
      at /home//-two/tool-suite/vscode-ide/packages/-vscode-ide/node_modules/monaco-page-objects/out/components/editor/SettingsEditor.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/monaco-page-objects/out/components/editor/SettingsEditor.js:4:12)
      at LinkSetting.setValue (node_modules/monaco-page-objects/out/components/editor/SettingsEditor.js:277:16)
      at /home//-two/tool-suite/vscode-ide/packages/-vscode-ide/out/test/ui/component/Home.test.js:35:27
      at Generator.next (<anonymous>)
      at /home//-two/tool-suite/vscode-ide/packages/-vscode-ide/out/test/ui/component/Home.test.js:8:71
      at new Promise (<anonymous>)
```

**Comment by jrichter1** [comment]
There is no value in `LinkSetting`, hence the error. It looks like the error message could be better, though.

Anyway, there is a link instead of value, you can click that with `openLink` and that's about it for `LinkSetting`.
