### ISSUE TITLE
Second test file not executed after successful first. How to debug ?

### ISSUE THREAD

**Issue by brianignacio5** [redhat-developer/vscode-extension-tester#336]
I'm trying to run some tests using your great package for a vscode extension but I'm running into some issues not sure how to debug. I'm trying to run `tsc -p && extent setup-and-run -l All out/ui-test/*-test.js` in Github Actions within a docker container but there is an error after running the first file (a helloworld-test.js same as the example notification in this repository) and the second test file never gets executed. Seems there is an unhandled error in `extest` but not sure how to debug the issue myself.

```
Shutting down the browser

Uninstalling vscode-extension-tester.api-handler...
Extension 'vscode-extension-tester.api-handler' was successfully uninstalled!
(node:520) UnhandledPromiseRejectionWarning: Canceled: Canceled
    at D (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:5:1157)
    at O.cancel (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:62880)
    at O.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63012)
    at N.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:9:63274)
    at d (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3655)
    at N.clear (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4133)
    at N.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4112)
    at dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4672)
    at dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:11:7330)
    at d (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3655)
    at /github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3843
    at /github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3942
    at Object.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:762)
    at d (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3788)
    at /github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:14:41520
    at Map.forEach (<anonymous>)
    at Ne.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:14:41496)
    at d (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:3655)
    at N.clear (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4133)
    at N.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4112)
    at S.dispose (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:6:4672)
    at Object.M [as main] (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cliProcessMain.js:17:38649)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async N (/github/workspace/test-resources/VSCode-linux-x64/resources/app/out/vs/code/node/cli.js:12:13842)
(Use `code --trace-warnings ...` to show where the warning was created)
(node:520) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:520) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

  1 passing (7s)

Done in 217.25s.

helloworld-test.js
helloworld-test.js.map
sdkconfig-test.js
sdkconfig-test.js.map
```

Will update with the test.log from test-resources folder. I haven't seen anywhere how can I find/debug the issue, if you could please point me to find out the root cause here will be very appreciated. 

For your information, I'm trying to capture an element in a web view in the second test file after opening a folder (is there a way to define the working directory of the ui-test code programmatically  or as an argument for `extest`?) which is need for my webview command to execute. I'm basically doing a `new Workbench().executeCommand(openFolder, testDirectoryVscodeUri)` and waiting for a bit. (This opening part seems to work locally on Windows 10 and failing on the test itself for the following reason)

I've also noticed that the code instance launched by the tests, when trying to run a task implemented with the Task API (For example a shell Execution) doesn't carry the env variables, perhaps by one of the disable flags arguments given to the code  executable launch. Is there some configuration to enable this ?

Thanks for your attention and sorry for the long post. I would really like to use your framework but still struggling a bit to get it right.

**Comment by jrichter1** [comment]
- Might be your shell is trying to expand the glob pattern before it actually gets passed into mocha. I'd suggest wrapping the glob in quotes like so `setup-and-run -l All 'out/ui-test/*-test.js'`.

- As far as the `UnhandledPromiseRejectionWarning` goes, don't worry about it. It's an issue in vscode CLI, it looks like it's already fixed in the insider stream.

- I haven't been able to start vscode with a folder open using webdriver so far. Even using CLI to add folders to the workspace instead opens a new window. So far we're stuck with opening files/folders the old fashioned way.

- AFAIK whether or not the build-in terminal inherits the environment is a setting in vscode (`terminal.integrated.inheritEnv`, although that one says it won't work for windows). Your code should still have access to the environment of the shell it was launched from though.

**Comment by brianignacio5** [comment]
Thanks for your reply. I've opted for `file: open folder` command approach. Is there a reason for not using `--extensionDevelopmentPath=/path/to/test/project` ?

With regards to the env. I'm not sure why is the case. Launching same `code` binary from `test-resources` directly will get the right env and the task runs properly. It might be some restriction/limitation running it from `extest` ?

**Comment by jrichter1** [comment]
The only difference `--extensionDevelopmentPath` makes is it turns the window blue instead of grey, don't ask why :)

But I decided to revisit the problem after reading this issue, and I might have found a way to add possibly multiple folders/files with a simple method call. Stay tuned for the next release.

Anyway, I haven't really had a chance to look into the environment situation yet. Do you have some sort of simple reproducer I could use for that?

**Comment by brianignacio5** [comment]
I've figured out the issue of env variable. I was using Path (for Windows) and the testing environment was using PATH (the linux/osx) and the env variable was not being update. This is an issue with my extension itself.

Thanks for your reply. I've resolved my issues, and I'll look forward for the next release.
