### ISSUE TITLE
Test execution fails with VSC 1.62.0 using Ubuntu 18.04

### ISSUE THREAD

**Issue by JSorella** [redhat-developer/vscode-extension-tester#385]
When Visual Studio Code 1.62.0 was released, then I have run my tests with the following command:
`extest setup-and-run`

Then, the Visual Studio Code 1.62.0 binary was downloaded by the tool (previously I was working with the 1.61.0), and the execution failed with the following stack trace:

```
`Error: Command failed: ELECTRON_RUN_AS_NODE=1 "/home/<my_user>/repos/<my_vsc_extension>/test-resources/VSCode-linux-x64/code" "/home/<my_user>/repos/<my_vsc_extension>/test-resources/VSCode-linux-x64/resources/app/out/cli.js" --install-extension "/home/<my_user>/repos/<my_vsc_extension>/<my_vsc_extension>-2.0.11.vsix"
    at checkExecSyncError (node:child_process:826:11)
    at Object.execSync (node:child_process:900:15)
    at CodeUtil.installExt (/home/<my_user>/repos/<my_vsc_extension>/node_modules/vscode-extension-tester/out/util/codeUtil.js:147:23)
    at CodeUtil.installExtension (/home/<my_user>/repos/<my_vsc_extension>/node_modules/vscode-extension-tester/out/util/codeUtil.js:127:14)
    at ExTester.<anonymous> (/home/<my_user>/repos/<my_vsc_extension>/node_modules/vscode-extension-tester/out/extester.js:79:30)
    at Generator.next (<anonymous>)
    at /home/<my_user>/repos/<my_vsc_extension>/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/<my_user>/repos/<my_vsc_extension>/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/home/<my_user>/repos/<my_vsc_extension>/node_modules/vscode-extension-tester/out/extester.js:58:16)`
```

When I run the tests using the previous binary and the `extest run-tests` command, the tests runs OK.

I am working with Ubuntu 18.04.6 LTS.

**Comment by jrichter1** [comment]
somebody decided to change the vscode CLI in a micro update :(
fix is in master, new release imminent
