### ISSUE TITLE
When vsce package --no-yarn in CodeUtil.packageExtension is failing, tests are not launched and error is not reported

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#388]
see https://app.circleci.com/pipelines/github/camel-tooling/vscode-camelk/1475/workflows/a28caad2-65f3-48a3-8367-225a9a90d0df/jobs/1802?invite=true#step-112-39

```
 ERROR  The following files have the same case insensitive path, which isn't supported by the VSIX format:
  - extension/LICENSE.txt
  - extension/LICENSE.txt
(node:37035) UnhandledPromiseRejectionWarning: Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at CodeUtil.packageExtension (/home/circleci/project/node_modules/vscode-extension-tester/out/util/codeUtil.js:190:23)
    at ExTester.<anonymous> (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:58:16)
    at ExTester.<anonymous> (/home/circleci/project/node_modules/vscode-extension-tester/out/extester.js:123:24)
```

**Comment by jrichter1** [comment]
Well, you are using the API, and the method does throw an error. I'd prefer to give the users freedom to handle that as they deem appropriate.

Now the issue is, nothing is handling that error in an async context. So you can either chain your call with a catch block, or you can intercept unhandled promises and do `process.exit(x)` if you want a non-zero exit code.

```typescript
process.on('unhandledRejection', error => {
    process.exit(1);
});
```
