### ISSUE TITLE
When install extension command is failing, provide error output

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#389]
for instance https://app.circleci.com/pipelines/github/jboss-fuse/vscode-atlasmap/647/workflows/557e49b9-d17c-47c6-8932-288cd1dbd546/jobs/854?invite=true#step-109-32
the install extension is failing (on the extension under test) but there is no information on the reasons. it would be nice to log the reason somewhere.

```
Error: Command failed: ELECTRON_RUN_AS_NODE=1 "/home/circleci/vscode-atlasmap/test-resources/VSCode-linux-x64/code" "/home/circleci/vscode-atlasmap/test-resources/VSCode-linux-x64/resources/app/out/cli.js" --install-extension "/home/circleci/vscode-atlasmap/atlasmap-viewer-0.1.0.vsix"
    at checkExecSyncError (child_process.js:790:11)
    at Object.execSync (child_process.js:863:15)
    at CodeUtil.installExt (/home/circleci/vscode-atlasmap/node_modules/vscode-extension-tester/out/util/codeUtil.js:131:23)
    at CodeUtil.installExtension (/home/circleci/vscode-atlasmap/node_modules/vscode-extension-tester/out/util/codeUtil.js:111:14)
    at ExTester.<anonymous> (/home/circleci/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:79:30)
    at Generator.next (<anonymous>)
    at /home/circleci/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/home/circleci/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/home/circleci/vscode-atlasmap/node_modules/vscode-extension-tester/out/extester.js:58:16)
 ```

**Comment by jrichter1** [comment]
Of course the output is being piped into stdout. It just doesn't help when there is no output.
