### ISSUE TITLE
Cannot execute helloworld-sample test: error ENOTFOUND update.code.visualstudio.com at setup stage

### ISSUE THREAD

**Issue by sleblanc38** [redhat-developer/vscode-extension-tester#395]
I have some issues to use the helloworld-sample test supplied in vscode-extension-tester:

1. After "npm install" in the vscode-extension-tester/sample-projects/helloworld-sample folder, "npm run compile" gives multiple errors like:
error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.
=> Adding "@types/mocha": "^9.0.0" to the "devDependencies" in package.json solves this first issue

2. "npm run ui-test" fails with the following error:
RequestError: getaddrinfo ENOTFOUND update.code.visualstudio.com
    at ClientRequest.<anonymous> (.../vscode-extension-tester/sample-projects/helloworld-sample/node_modules/got/dist/source/core/index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (.../vscode-extension-tester/sample-projects/helloworld-sample/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

My environment is as follow:
- Linux RHEL7
- node-linux-x64-16.13.0
- VSCode-linux-x64-1.62.3

Could you please help to understand/solve this issue ?
Thanks !

**Comment by yannickowow** [comment]
Hello,
it looks like `got` does not support proxies / ca out of the box.
To work around this issue, I've tried the following:
- npm install global-agent (https://github.com/gajus/global-agent)
- export GLOBAL_AGENT_HTTP_PROXY=http://<proxy>
- in Download (.js) file
   - added `import 'global-agent/bootstrap'`;
This allows `got` to support proxy settings.

Regards

**Comment by jrichter1** [comment]
I guess it's been too long since we've had a proxy issue.

@yannickowow PR would be most welcome
