### ISSUE TITLE
Upgrade nut-tree to a version compatible with node 16

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#396]
seems to be version 1.7.0
https://github.com/nut-tree/nut.js/blob/develop/CHANGELOG.md#170

it will avoid this kind of error when building with node 16+ project depending on vscode-extension-tester:
```
npm ERR! code 1
npm ERR! path /home/lheinema/git/vscode-atlasmap/node_modules/opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform linux
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/lheinema/.npm/_logs/2021-11-25T09_38_42_795Z-debug.log
npm ERR! child_process.js:674
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Command failed: npm install @nut-tree/opencv-build-linux@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/lheinema/.npm/_logs/2021-11-25T09_38_42_795Z-debug.log
npm ERR! 
npm ERR!     at checkExecSyncError (child_process.js:635:11)
npm ERR!     at execSync (child_process.js:671:15)
npm ERR!     at install (/home/lheinema/git/vscode-atlasmap/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (/home/lheinema/git/vscode-atlasmap/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:26:5)
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:999:30)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:863:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
npm ERR!     at internal/main/run_main_module.js:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(373) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
npm ERR!       117, 120,  64, 117,
npm ERR!       ... 273 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 15547,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(373) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
npm ERR!     117, 120,  64, 117,
npm ERR!     ... 273 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lheinema/.npm/_logs/2021-11-25T09_38_43_727Z-debug.log
```

**Comment by jrichter1** [comment]
you do realize that native package is already deprecated and everyone should avoid it?

**Comment by apupier** [comment]
> you do realize that native package is already deprecated and everyone should avoid it?

I didn't know. I will see if i can remove the dependency in our projects

**Comment by apupier** [comment]
dependency on vscode-extension-tester-native has been removed in vscode-uitests-tooling, VS Code Camel K and VS Code Language Support for Apache Camel
