### ISSUE TITLE
VSCode modified the terminal css selector ?

### ISSUE THREAD

**Issue by brianignacio5** [redhat-developer/vscode-extension-tester#401]
In my code I have:
```
const terminalView = await panel.openTerminalView();
await new Promise((res) => setTimeout(res, 100000));
await terminalView.getCurrentChannel();
const text = await terminalView.getText();
```
which results in this:
```
Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".integrated-terminal"}
  (Session info: chrome=91.0.4472.164)
  (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Linux 5.11.0-1021-azure x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /github/workspace/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:85:5)
  From: Task: WebElement.findElement(By(css selector, .integrated-terminal))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at BottomBarPanel.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at BottomBarPanel.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
      at new ElementWithContexMenu (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:19:1)
      at new ChannelView (node_modules/monaco-page-objects/out/components/bottomBar/AbstractViews.js:19:1)
      at new TerminalView (node_modules/monaco-page-objects/out/components/bottomBar/Views.js:100:9)
      at BottomBarPanel.<anonymous> (node_modules/monaco-page-objects/out/components/bottomBar/BottomBarPanel.js:87:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/bottomBar/BottomBarPanel.js:5:58)
```

Using the vscode Developer tools I've noticed that the terminal has `<div id="terminal"> </div>`

**Comment by brianignacio5** [comment]
Was a timing issue, apologies.
