### ISSUE TITLE
[🚫 Bug] Failed when call `debugView.getText()`, only on macOS

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#408]
version: 
```
    "robotjs": "^0.6.0",
    "typescript": "^4.4.3",
    "vscode-extension-tester": "^4.2.0"
```

vscode version:

```
    "installdriver": "extest get-chromedriver -s test-resources -c 1.63.0",
    "installvscode": "extest get-vscode -s test-resources -c 1.63.0",
```

code: 

```
  const outputView = await new Workbench().getBottomBar().openDebugConsoleView();
    let output = await outputView.getText();
```

```
  Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-menu-container"}
  (Session info: chrome=91.0.4472.164)
  (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Mac OS X 11.3.0 arm64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /Users/hh/code/ide/ui-test/node_modules/selenium-webdriver/lib/http.js:441:30
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-menu-container))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
      at new Menu (node_modules/monaco-page-objects/out/components/menu/Menu.js:17:1)
      at new ContextMenu (node_modules/monaco-page-objects/out/components/menu/ContextMenu.js:20:9)
      at DebugConsoleView.<anonymous> (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:44:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:5:58)
      at runMicrotasks (<anonymous>)

```

**Comment by zhfnjust** [comment]
failed on linux 

```

 1) Test Debugging
       debug:all should finish the debugging successfully:
     CancellationError: There was an uncaught error in the control flow: NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="workbench\.panel\.repl"]"}
  (Session info: chrome=91.0.4472.164)
  (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Linux 5.4.0-1058-gcp x86_64)
      at Function.wrap (node_modules/selenium-webdriver/lib/promise.js:749:14)
      at ManagedPromise.cancel (node_modules/selenium-webdriver/lib/promise.js:1265:38)
      at TaskQueue.abort_ (node_modules/selenium-webdriver/lib/promise.js:3013:34)
      at ControlFlow.cancelQueues_ (node_modules/selenium-webdriver/lib/promise.js:2643:11)
      at ControlFlow.onQueueError_ (node_modules/selenium-webdriver/lib/promise.js:2618:10)
      at TaskQueue.emit (node_modules/selenium-webdriver/lib/events.js:62:21)
      at TaskQueue.abort_ (node_modules/selenium-webdriver/lib/promise.js:3018:12)
      at TaskQueue.processUnhandledRejections_ (node_modules/selenium-webdriver/lib/promise.js:3116:12)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3029:40)
      at /home/travis/build/sCrypt-Inc/ide/ui-test/node_modules/selenium-webdriver/lib/promise.js:2927:27
  From: Task: getsCryptDebugOutput timeout text:
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at /home/travis/build/sCrypt-Inc/ide/ui-test/out/util.js:543:74
      at Generator.next (<anonymous>)
      at /home/travis/build/sCrypt-Inc/ide/ui-test/out/util.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (out/util.js:4:12)
      at getsCryptDebugOutput (out/util.js:542:12)
      at Suite.<anonymous> (out/debug-all.test.js:38:66)
```

**Comment by odockal** [comment]
Is this issue still actual? Is it something we should take a look or did you manage to find a solution? Thanks.

**Comment by fjakobs** [comment]
I still see it and it's currently blocking me.

**Comment by djelinek** [comment]
tested with latest VS Code `1.84` and latest vscode-extension-tester `5.10.0`, works as expected

```
const view = await new BottomBarPanel().openDebugConsoleView();
const text = await view.getText();
```

but we wre missing test for `debugConsole.getText()` method, which I will add as resolution ofr this issue.
Thank you

**Comment by djelinek** [comment]
tested with latest VS Code `1.84` and latest vscode-extension-tester `5.10.0`, works as expected

```
const view = await new BottomBarPanel().openDebugConsoleView();
const text = await view.getText();
```

but we wre missing test for `debugConsole.getText()` method, which I will add as resolution ofr this issue.
Thank you
