### ISSUE TITLE
RequestError: getaddrinfo ENOTFOUND update.code.visualstudio.com

### ISSUE THREAD

**Issue by kapinnow** [redhat-developer/vscode-extension-tester#412]
execution of helloworld-sample>npm run ui-test does yield this 

RequestError: getaddrinfo ENOTFOUND update.code.visualstudio.com
    at ClientRequest.<anonymous> (D:\Re-X\vsctest\vscode-extension-tester-master\sample-projects\helloworld-sample\node_modules\got\dist\source\core\index.js:962:111)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (D:\Re-X\vsctest\vscode-extension-tester-master\sample-projects\helloworld-sample\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

any ideas what may get wrong here?

**Comment by odockal** [comment]
resources: https://github.com/redhat-developer/vscode-extension-tester/wiki/Debugging-Tests

**Comment by djelinek** [comment]
Could you provide us with more info about your environment please?

- node version?
- vscode version?
- vscode-extension-tester version?

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
