### ISSUE TITLE
Reliability issues when calling api.runTests multiple times

### ISSUE THREAD

**Issue by Mac-Genius** [redhat-developer/vscode-extension-tester#421]
- vscode-extension-tester version: **4.2.3**
- vscode version: **1.63.2**
- Platform: **Windows NT 10.0.18363 x86_64**

I'm trying to use the `ExTester` api to run tests. I have two test files and I have a middle step that run between the tests, so my code looks something like this to start the tests:

```javascript
api.runTests('dist/tests/customEditor1-test.js');
runSomethingElse();
api.runTests('dist/tests/customEditor2-test.js');
```

At this point the files are identical and are testing a CustomEditor:

```javascript
// customEditor-test.js

describe('Test Editor', () => {
    let customEditor: CustomEditor;
    before(async () => {
        customEditor = new CustomEditor();
    });

    it('Get field', async () => {
        const webview = customEditor.getWebView();
        await webview.switchToFrame();
        const element = await webview.findWebElement(By.className('element'));
        expect(await element.getText()).equals('Hello World');
        await webview.switchBack();
    });
});
```
The first test runs fine, but the second test fails with the following error:

```bash
NoSuchWindowError: no such window
(Session info: chrome=91.0.4472.101)
(Driver info: chromedriver=91.0.4472.101 (...),platform=Windows NT 10.0.18363 x86_64)
    at Object.checkLegacyResponse (node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:509:13)
    at C:\path\to\project\node_modules\selenium\webdriver\lib\http.js:441:30
    at processTickAndRejections (internal/process/task_queues.js:95:5)
From: Task WebDriver.switchTo().window(CDwindow-<hash>)
    at Driver.schedule (node_modules\selenium-webdriver\lib\webdriver.js:807:17)
    at TargetLocator.window (node_modules\selenium-webdriver\lib\webdriver.js:1844:25)
    at WebView.<anonymous> (node_modules\monaco-page-objects\out\components\editor\WebView.js:88:48)
    at Generator.next (<anonymous>)
    at C:\path\to\project\node_modules\monaco-page-objects\out\components\editor\WebView.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (node_modules\monaco-page-objects\out\components\editor\WebView.js:4:12)
    at WebView.switchBack (nodes_modules\monaco-page-objects\out\components\editor\WebView.js:84:16)
    at <the test function>
```

Is it possible to call `runTest` multiple times in a row? Perhaps the chrome driver instance isn't being cleaned up between tests?

**Comment by djelinek** [comment]
Closing - no issue activity for a long time. Feel free to reopen if needed.
