### ISSUE TITLE
SideBarView().getContent().getSection("xxx").moreActions() is not working

### ISSUE THREAD

**Issue by gpsaraiva** [redhat-developer/vscode-extension-tester#422]
new SideBarView().getContent().getSection("xxx").moreActions() is not working

When trying to interact with the moreActions() of a context menu, an error is raised:

Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-menu-container"}
  (Session info: chrome=91.0.4472.164)
  (Driver info: chromedriver=91.0.4472.101 (af52a90bf87030dd1523486a1cd3ae25c5d76c9b-refs/branch-heads/4472@{#1462}),platform=Mac OS X 11.6.0 x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /Users/guilhermesaraiva/mysql-client-qa/Mocha/extension/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-menu-container))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElement.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElement.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/monaco-page-objects/out/components/AbstractElement.js:39:48)
      at new Menu (node_modules/monaco-page-objects/out/components/menu/Menu.js:17:1)
      at new ContextMenu (node_modules/monaco-page-objects/out/components/menu/ContextMenu.js:20:9)
      at ActivityBar.<anonymous> (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:44:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/monaco-page-objects/out/components/ElementWithContextMenu.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

I think the issue comes from Context Menus. When trying to use the .openContextMenu() , the error is the same - cannot find that selector.

**Comment by odockal** [comment]
@gpsaraiva Hi there! Thanks for reporting, I am afraid that you are encountering mac os limitations: https://github.com/redhat-developer/vscode-extension-tester/blob/b56c96b108552954115990f3fc1bfede3e229412/README.md#requirements.
