### ISSUE TITLE
Reuse package script of package.json or propagate arguments of vsce

### ISSUE THREAD

**Issue by RovoMe** [redhat-developer/vscode-extension-tester#441]
I'm working on a company-private extension that is hosted on a company-run and not publicly accessible Gitlab server. This project contains a README with a couple of links to images located in the project itself. In order to package the extension via `npm run package` I have to specify `--baseContentUrl` and `--baseImageUrl` as otherwise `vsce` claims that the images can't be found and (stupidly) fails the build.

The general scripts sections in the `package.json` looks like this:

```json
"scripts": {
    "clean": "rm -rf out",
    "lint": "eslint ./src --ext .ts,.tsx",
    "autofix": "npm run clean && eslint --fix ./src --ext .ts,.tsx",
    "esbuild": "esbuild ./src/extension.ts --bundle --outfile=out/extension.js --external:vscode --platform=node --target=node14.18 --sourcemap",
    "esbuild-watch": "npm run esbuild -- --watch",
    "compile": "npx tsc -p ./ && npm run esbuild",
    "watch": "npx tsc -watch -p ./ && npm run esbuild-watch",
    "watch-compile": "tsc -p ./ && npm run esbuild-watch",
    "check": "npx tsc --project . --noEmit",
    "pretest": "npm run compile && npm run lint",
    "unit-tests": "mocha --require ts-node/register spec/unit/**/*.ts",
    "ui-tests": "npm run compile && extest setup-and-run out/spec/ui-tests/ui-test.js --mocha_config ./spec/ui-tests/.mocharc-debug.js --install_dependencies --type insider --code_settings ./spec/ui-tests/settings.json",
    "test": "npm run unit-tests && npm run ui-tests",
    ...
    "vscode:prepublish": "npm run esbuild -- --minify",
    "package": "vsce package --out release/ --baseContentUrl https://path/to/gitlab/repo --baseImagesUrl https://path/to/gitlab/repo/-/raw/master --"
}
```

As the project itself is not publicly accessible the definition of `--baseContentUrl` and `--baseImagesUrl` is unfortunately necessary else `vsce` refuses to create the VSIX artifact. With these settings I am able to generate the VSIX file representing the VSCode extension.

However, on trying to run a simple ui-test via `npm run ui-tests` I'm presented with the following output:

```console
ERROR  Couldn't detect the repository where this extension is published. The image 'images/logo.png' will be broken in README.md. GitHub/GitLab repositories will be automatically detected. Otherwise, please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.
Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:760:11)
    at Object.execSync (child_process.js:833:15)
```

which is basically the result of [this code](https://github.com/redhat-developer/vscode-extension-tester/blob/bfa2a58d384f43ebac1ac50e31df5615fb9fa7ac/src/util/codeUtil.ts#L189-L196).

If I remove all links in the README to images and links to the project itself I am able to run the UI tests via the `npm run ui-tests` script. However, with a `launch.json` configuration like this 

```json
{
    "name": "Debug UI Tests",
    "type": "node",
    "request": "launch",
    "program": "${workspaceFolder}/node_modules/.bin/extest",
    "args": [
        "setup-and-run",
        "${workspaceFolder}/out/spec/ui-tests/ui-test.js",
	"--mocha_config",
	"${workspaceFolder}/spec/ui-tests/.mocharc-debug.js",
	"--install_dependencies",
	"--type",
	"insider",
	"--code_settings",
	"${workspaceFolder}/spec/ui-tests/settings.json"
    ],
    "outFiles": [
        "${workspaceFolder}/out/spec/**/*.js"
    ],
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen",
    "preLaunchTask": "npm: compile"
}
```

which is basically just a slight adaptation of the one used in the `helloworld` sample project which does launch the UI tests from VSCode, and uses the same input arguments as the command specified in the scripts section I end up with an output like this:

```console
...
> npm run esbuild -- --minify

Debugger attached.
...
> esbuild ./src/extension.ts --bundle --outfile=out/extension.js --external:vscode --platform=node --target=node14.18 --sourcemap "--minify"


  out/extension.js      307.2kb
  out/extension.js.map  641.9kb

⚡ Done in 74ms
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
 ERROR  Command failed: npm list --production --parseable --depth=99999 --loglevel=error
Debugger attached.
npm ERR! missing: domelementtype@1.3.1, required by domhandler@2.4.2
npm ERR! missing: @types/node@17.0.30, required by @types/htmlparser2@3.10.3
npm ERR! missing: domelementtype@1.3.1, required by domhandler@2.4.2
npm ERR! missing: domelementtype@2.3.0, required by domhandler@4.3.1
npm ERR! missing: dom-serializer@1.4.1, required by domutils@2.8.0
npm ERR! missing: domelementtype@2.3.0, required by domutils@2.8.0
npm ERR! missing: domhandler@4.3.1, required by domutils@2.8.0
npm ERR! missing: domelementtype@2.3.0, required by dom-serializer@1.4.1
npm ERR! missing: domhandler@4.3.1, required by dom-serializer@1.4.1
npm ERR! missing: domelementtype@2.3.0, required by htmlparser2@7.2.0
npm ERR! missing: domhandler@4.3.1, required by htmlparser2@7.2.0
Waiting for the debugger to disconnect...

Waiting for the debugger to disconnect...
Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:760:11)
    at Object.execSync (child_process.js:833:15)
    at CodeUtil.packageExtension (.../node_modules/vscode-extension-tester/out/util/codeUtil.js:170:23)
    at ExTester.<anonymous> (.../node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at .../node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (.../node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (.../node_modules/vscode-extension-tester/out/extester.js:58:16)
    at ExTester.<anonymous> (.../node_modules/vscode-extension-tester/out/extester.js:123:24)
```

As the error occurs at the time the VSIX is packaged in the `npm run ui-tests` case I assume this is somehow due to ExTester using also its own `vsce package` call.

So I guess it would be beneficial to either "reuse" the `package` definition in the script-section, if available, or allow to specify these options as part of the `setup-and-run` command.

**Comment by RovoMe** [comment]
Thank you for your suggestion. I changed the test runner to the following code: 

```typescript
import { ExTester, ReleaseQuality } from "vscode-extension-tester";
import * as path from "path";
import pjson from '../../package.json';

async function main() {

    const artifact = pjson.name + "-" + pjson.version + ".vsix";
    const vsixFile = path.resolve(__dirname, '..', '..', '..', 'release', artifact);
    console.log(`VSIX location: ${vsixFile}`);

    const tester = new ExTester(undefined, ReleaseQuality.Insider, undefined);
    await tester.downloadCode();
    await tester.downloadChromeDriver();
    await tester.installVsix({
        vsixFile: vsixFile,
        useYarn: false
    });
    await tester.setupRequirements({ installDependencies: true });
    await tester.runTests('out/spec/ui-tests/ui-test.js', {
        config: 'spec/ui-tests/.mocharc-debug.js',
        settings: 'spec/ui-tests/settings.json'
    });
}

main().catch(err => console.error(err));
```
and updated the script in the `package.json` to a simple `"ui-tests": "node out/spec/ui-tests/runTests.js"` test runner invocation.

When I now issue the following command: `npm run clean && npm run compile && npm run lint && npm run package" with the links in the README enabled, the packaging succeeds and the VSIX file can be found in the `release/` directory afterwards.

If I now add the ui-tests to that command chain (`npm run clean && npm run compile && npm run lint && npm run package && npm run ui-tests`) ExTester seems to try to build its own VSIX artifact though:

```console
> esbuild ./src/extension.ts --bundle --outfile=out/extension.js --external:vscode --platform=node --target=node14.18 --sourcemap "--minify"


  out/extension.js      307.6kb
  out/extension.js.map  643.4kb

⚡ Done in 29ms
 DONE  Packaged: release/myExtension-1.0.5.vsix (292 files, 3.17MB)

> myExtension@1.0.5 ui-tests
> node out/spec/ui-tests/runTests.js

VSIX location: /path/to/extension/dir/release/myExtension-1.0.5.vsix
VS Code exists in local cache, skipping download
ChromeDriver 98.0.4758.102 exists in local cache, skipping download
Installing extensions...
(node:1831713) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code-insiders --trace-deprecation ...` to show where the warning was created)
Extension 'myExtension-1.0.5.vsix' was successfully installed.
VS Code exists in local cache, skipping download
ChromeDriver 98.0.4758.102 exists in local cache, skipping download
Executing prepublish script 'npm run vscode:prepublish'...

> myExtension@1.0.5 vscode:prepublish
> npm run esbuild -- --minify


> myExtension@1.0.5 esbuild
> esbuild ./src/extension.ts --bundle --outfile=out/extension.js --external:vscode --platform=node --target=node14.18 --sourcemap "--minify"


  out/extension.js      307.6kb
  out/extension.js.map  643.4kb

⚡ Done in 32ms
 ERROR  Couldn't detect the repository where this extension is published. The image 'images/logo.png' will be broken in README.md. GitHub/GitLab repositories will be automatically detected. Otherwise, please provide the repository URL in package.json or use the --baseContentUrl and --baseImagesUrl options.
Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (child_process.js:760:11)
    at Object.execSync (child_process.js:833:15)
    at CodeUtil.packageExtension (/path/to/extension/dir/node_modules/vscode-extension-tester/out/util/codeUtil.js:170:23)
    at ExTester.<anonymous> (/path/to/extension/dir/node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /path/to/extension/dir/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/path/to/extension/dir/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix /path/to/extension/dir/node_modules/vscode-extension-tester/out/extester.js:58:16)
    at ExTester.<anonymous> (/path/to/extension/dir/node_modules/vscode-extension-tester/out/extester.js:123:24) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1831747,
  stdout: null,
  stderr: null
}
```

Interestingly, ExTester installed the VSIX artifact already successfully but then seems to trigger a further `vscode:prepublish` action followed by a `vsce package --no-yarn`. If the links are commented out in the README by obfuscating the actual link the command chain actually triggers the UI tests though the VSIX is build also twice, once as part of the `npm run package` instruction and once as part of the `runTests.js` code even though I don't see a which of those ExTester functions is actually triggering the VSIX build.

**Comment by jrichter1** [comment]
Would it help to define the vsce options in your package.json as shown is [vsce documentation](https://github.com/microsoft/vscode-vsce#configuration)?

**Comment by RovoMe** [comment]
Thank you Jan, it seems this way of specifying the arguments works but I have removed the `setupRequirements` function call from the test runner though as I don't seem to really need it with this setup anyway and a second VSIX generation is also a bit meh.

Interestingly VSCode doesn't provide any code completion support for this setting and as such slipped obviously through my radar.
