### ISSUE TITLE
Fix unstable scmView test

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-extension-tester#448]
```
2) SCM View
       getProviders works:
     AssertionError: expected [] not to be empty
      at /home/runner/work/vscode-extension-tester/vscode-extension-tester/test/test-project/out/src/test/xsideBar/scmView-test.js:48:42
      at Generator.next (<anonymous>)
      at fulfilled (out/src/test/xsideBar/scmView-test.js:24:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
  3) SCM View
       getProvider works:
     AssertionError: expected undefined not to be undefined
      at /home/runner/work/vscode-extension-tester/vscode-extension-tester/test/test-project/out/src/test/xsideBar/scmView-test.js:52:41
      at Generator.next (<anonymous>)
      at fulfilled (out/src/test/xsideBar/scmView-test.js:24:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Ref: https://github.com/redhat-developer/vscode-extension-tester/runs/7041405848

**Comment by mlorinc** [comment]
Closing as it is not relevant anymore.
