### ISSUE TITLE
Getting Error: Request returned status code: 404 while running simple hello-world example

### ISSUE THREAD

**Issue by ajcrypto** [redhat-developer/vscode-extension-tester#468]
`npm run ui-test`

> devtools-vscode-automation@0.0.1 ui-test /Users/ajinkyapande/Ajinkya/Ochain/obp-qa-devtools
> MOCHAWESOME_REPORTFILENAME=AutomationReport MOCHAWESOME_REPORTTITLE=MyReport extest  setup-and-run out/ui-test/final-demo.js -m .mocharc.js

```
Error: Request returned status code: 404
Details: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /api/releases/stable</pre>
</body>
</html>

```
```
    at Request._callback (/Users/ajinkyapande/Ajinkya/Ochain/obp-qa-devtools/node_modules/vscode-extension-tester/out/util/codeUtil.js:62:33)
    at Request.self.callback (/Users/ajinkyapande/Ajinkya/Ochain/obp-qa-devtools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/Users/ajinkyapande/Ajinkya/Ochain/obp-qa-devtools/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/Users/ajinkyapande/Ajinkya/Ochain/obp-qa-devtools/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! devtools-vscode-automation@0.0.1 ui-test: `MOCHAWESOME_REPORTFILENAME=AutomationReport MOCHAWESOME_REPORTTITLE=MyReport extest  setup-and-run out/ui-test/final-demo.js -m .mocharc.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the devtools-vscode-automation@0.0.1 ui-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ajinkyapande/.npm/_logs/2022-07-13T12_02_50_705Z-debug.log
ajpande-mac:obp-qa-devtools ajinkyapande$ 
```

**Comment by odockal** [comment]
@ajcrypto Hey, can you please retry it again? It simply seems like given url was not available at the moment. It works for me.
