### ISSUE TITLE
Looking up actions via label-name is broken

### ISSUE THREAD

**Issue by RovoMe** [redhat-developer/vscode-extension-tester#482]
I have a vscode extension that I want to test with this library. I wrote some tests a couple month ago that test a treeview that allows to CRUD some tags. VSCode generates a HTML output for a tree item that looks similar to the code below:

```html
<div class="monaco-tl-row align-icon-with-twisty">
    <div class="monaco-tl-indent" style="width: 0px;"></div>
    <div class="monaco-tl-twistie" style="padding-left: 8px;"></div>
    <div class="monaco-tl-contents custom-view-tree-node-item">
        <div class="custom-view-tree-node-item-icon" style="background-image: url(&quot;vscode-file://vscode-app/some/path/resources/dark/tag.svg&quot;);"></div>
        <div class="monaco-icon-label custom-view-tree-node-item-resourceLabel">
            <div class="monaco-icon-label-container">
                <span class="monaco-icon-name-container">
                    <a class="label-name">
                        <span class="monaco-highlighted-label">
                            <span>Some Tag</span>
                        </span>
                    </a>
                </span>
                <span class="monaco-icon-description-container"></span>
            </div>
            <div class="actions">
                <div class="monaco-action-bar animated">
                    <ul class="actions-container" role="toolbar">
                        <li class="action-item menu-entry" role="presentation">
                            <a class="action-label icon" role="button" aria-label="Edit" title="Edit" tabindex="0" style="background-image: url(&quot;vscode-file://vscode-app/some/path/resources/dark/edit.svg&quot;);"></a>
                        </li>
                        <li class="action-item menu-entry" role="presentation">
                            <a class="action-label codicon codicon-trash" role="button" aria-label="Delete" title="Delete"></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
```

Now, when I test this via `vscode-extension-tester` with a code that looks like this

```typescript
const tagTree = await content.getSection('Tags') as CustomTreeSection;
const items = await tagTree.getVisibleItems();
const action = await items[0].getActionButton('Edit');
if (action) {
    await action.click();
    ...
} else {
    fail('No action available to edit selected tag');
}
```
I get this error in return as no action with the given label could be found:

```
AssertionError [ERR_ASSERTION]: No action available to edit selected tag
      at /.../out/spec/ui-tests/tagView.test.js:276:39
      ...
```

Checking the length of `items[0].getActionButtons()` returns the expected two actions defined on that tag item. If I change the test code to

```typescript
const tagTree = await content.getSection('Tags') as CustomTreeSection;
const items = await tagTree.getVisibleItems();
const actions = await items[0].getActionButtons();
const action = actions[0]; 
if (action) {
    await action.click();
    ...
}
...
```

the error changes to 

```
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//a[contains(@class, 'action-label') and @role='button' and @title='']"}
  (Session info: chrome=102.0.5005.167)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:589:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:514:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:740:17)
      at async toWireValue (node_modules/selenium-webdriver/lib/webdriver.js:141:15)
      ...
```
While looking up actions on the `tagTree` itself via `const action = await tagTree.getAction('Some Name');` shares the same behavior as action buttons on tree items, at least the workaround on using the array index allowed the code, which worked in the past, to work. I also tried to print the names of the available actions via `action.getLabel()` or `action.getText()` but both just return an empty string.

As mentioned, the code worked in the past and is now broken after returning from a month of vacation and some VSCode and dependency updates.

OS: Ubuntu 20.04.4 LTS
VSCode: 1.69.2
vscode-extension-tester: 4.4.1
node: v16.15.1
npm: 8.11.0

**Comment by mituan25** [comment]
I got the same problem. Can anyone help?
Thanks!

**Comment by katsoohoo** [comment]
I'm facing the same issue as well. This seems to be a Linux-specific error since I'm able to run my test cases successfully on macOS 12.6, but they fail in a Debian-based Docker container with vscode-extension-tester 5.1.0.
```sh
❯ docker run circleci/node:lts-browsers /bin/bash -c "cat /etc/*release*"
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

With vscode-extension-tester 4.4.0, I can verify that `ViewItemAction.getLabel()` returns the correct string. But with vscode-extension-tester 5.1.0, it returns `null`.

**Comment by ada345** [comment]
I'm still unable to get the action button with `getActionButton('Name')` in 5.2.0

**Comment by djelinek** [comment]
@ada345 latest extester version is 5.6.0. In case you will be able to reproduce with latest version, please feel free to reopen this issue.
