### ISSUE TITLE
ViewSection expansion not working in latest VSCode 1.41.x

### ISSUE THREAD

**Issue by lakxraju** [redhat-developer/vscode-extension-tester#51]
Cannot expand ViewSection and get tree item from ViewSection (under a Tree view)

**Note**: this error exists only in the latest VSCode (1.41.x). Older version (1.40.2) works fine

What I am doing:

```
const section = await new SideBarView().getContent().getSection(<section_name>);
await section.expand();
 if (await section.isExpanded()) {
      console.debug('Section expanded');
      const item = await section.findItem(<Item Name>);
      await item.click();
}
```
Here is the error:

```
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".panel-header"}
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Mac OS X 10.14.6 x86_64)
    at Object.checkLegacyResponse (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/selenium-webdriver/lib/http.js:441:30
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From: Task: WebElement.findElement(By(css selector, .panel-header))
    at Driver.schedule (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at CustomTreeSection.schedule_ (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
    at CustomTreeSection.findElement (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
    at CustomTreeSection.<anonymous> (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/vscode-extension-tester/out/webdriver/components/sidebar/ViewSection.js:103:39)
    at Generator.next (<anonymous>)
    at /Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/vscode-extension-tester/out/webdriver/components/sidebar/ViewSection.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/vscode-extension-tester/out/webdriver/components/sidebar/ViewSection.js:4:12)
    at CustomTreeSection.isHeaderHidden (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/vscode-extension-tester/out/webdriver/components/sidebar/ViewSection.js:102:16)
    at CustomTreeSection.<anonymous> (/Users/lakshraj/IdeaProjects/dslink-cpp-normalization/vscode_extension/node_modules/vscode-extension-tester/out/webdriver/components/sidebar/ViewSection.js:38:28)
```

**Comment by jrichter1** [comment]
Updates just landed in master, will be included in the next release.
