### ISSUE TITLE
 WebDriverError: unknown error: Chrome failed to start: crashed.

### ISSUE THREAD

**Issue by zhfnjust** [redhat-developer/vscode-extension-tester#517]
> Define issue title **short** and **most specific** to the problem.

> Tag each new issue with relevant **LABELS** (*bug*, *enhancement*, etc.).

> Replace all **???** with relevant information.

## Expected Behavior
- started

## Actual Behavior
- crash

## Steps to Reproduce the Problem

<img width="1780" alt="image" src="https://user-images.githubusercontent.com/995909/193000988-b86c4baf-8242-4234-873f-bcef7095ded6.png">

it can start on macOs and windows. only happen on linux (ubuntu bionic),

## Specifications

    "installdriver": "extest get-chromedriver -s test-resources -c 1.70.1",
    "installvscode": "extest get-vscode -s test-resources -c 1.70.1",

  - VSCode version: ???
  - ExTester version: ???
  - Platform: 
      - [x] Linux
      - [ ] macOS
      - [ ] Windows

**Comment by kiwi-bui** [comment]
I am also experiencing this issue(tried on v4.3.0 and v5.2.1). Has anybody found a solution?

I am running this in a github action linux runner:
`extest get-vscode && extest get-chromedriver && extest install-vsix --extensions_dir ./test-resources/extensions --vsix_file ./dist/vscode-extension.vsix && extest install-from-marketplace --extensions_dir ./test-resources/extensions redhat.java vscjava.vscode-java-debug redhat.vscode-yaml && extest run-tests ./out/test/runPackageTests.js`


I am getting essentially the same output:
```
Writing code settings to /home/runner/work/tanzu-developer-tools-for-vscode/tanzu-developer-tools-for-vscode/test-resources/settings/User/settings.json
Launching browser...
  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (336ms)
  2 failing

  1) "before all" hook in "{root}":
     WebDriverError: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/runner/work/tanzu-developer-tools-for-vscode/tanzu-developer-tools-for-vscode/test-resources/VSCode-linux-x64/code is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:587:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:515:28)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) "after all" hook in "{root}":
     TypeError: Cannot read property 'manage' of undefined
      at VSBrowser.<anonymous> (node_modules/vscode-extension-tester/out/browser.js:126:48)
      at Generator.next (<anonymous>)
      at /home/runner/work/tanzu-developer-tools-for-vscode/tanzu-developer-tools-for-vscode/node_modules/vscode-extension-tester/out/browser.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/browser.js:4:12)
      at VSBrowser.quit (node_modules/vscode-extension-tester/out/browser.js:125:16)
      at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:82:35)
      at Generator.next (<anonymous>)
      at /home/runner/work/tanzu-developer-tools-for-vscode/tanzu-developer-tools-for-vscode/node_modules/vscode-extension-tester/out/suite/runner.js:8:71
      at new Promise (<anonymous>)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tanzu@0.13.0 test-package: `npm run test-package-get-resources && npm run test-package-install-extension && extest run-tests ./out/test/runPackageTests.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tanzu@0.13.0 test-package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-01-24T08_[46](https://github.com/vmware-tanzu/tanzu-developer-tools-for-vscode/actions/runs/3994410146/jobs/6852088986#step:21:47)_21_[63](https://github.com/vmware-tanzu/tanzu-developer-tools-for-vscode/actions/runs/3994410146/jobs/6852088986#step:21:64)4Z-debug.log
```

**Comment by LongOddCode** [comment]
+1

**Comment by djelinek** [comment]
Duplicates #485
