### ISSUE TITLE
The `onCancel` handler was attached after the promise settled.

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#524]
## Expected Behavior
- no error during build

## Actual Behavior
- failing build with stack:

```

> atlasmap-viewer@0.2.3 ui-test
> extest setup-and-run out/ui-test/all.js --storage uitest-resources --code_settings ./src/ui-test/settings.json --uninstall_extension

Downloading VSCode: latest
Downloading VS Code from: https://update.code.visualstudio.com/latest/darwin/stable
progress: 0/118 (0%)
/Users/runner/work/vscode-atlasmap/vscode-atlasmap/node_modules/p-cancelable/index.js:48
					throw new Error('The `onCancel` handler was attached after the promise settled.');
					      ^

Error: The `onCancel` handler was attached after the promise settled.
    at onCancel (/Users/runner/work/vscode-atlasmap/vscode-atlasmap/node_modules/p-cancelable/index.js:48:12)
    at makeRequest (/Users/runner/work/vscode-atlasmap/vscode-atlasmap/node_modules/got/dist/source/as-promise/index.js:38:13)
    at Request.<anonymous> (/Users/runner/work/vscode-atlasmap/vscode-atlasmap/node_modules/got/dist/source/as-promise/index.js:143:17)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:513:28)
    at Timeout.retry (/Users/runner/work/vscode-atlasmap/vscode-atlasmap/node_modules/got/dist/source/core/index.js:1278:30)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
 ```

## Steps to Reproduce the Problem

 I don't know, it is randomly appearing on CI.

## Specifications

  - VSCode version: ???
  - ExTester version: ???
  - Platform: 
      - [ ] Linux
      - [x] macOS
      - [ ] Windows

**Comment by fjakobs** [comment]
Seems to be related to https://github.com/sindresorhus/got/issues/1489

**Comment by djelinek** [comment]
Closing - did not see for a long time. Feel free to reopen if needed.
