### ISSUE TITLE
[Bug] Identifying chromium driver from manifest.json step fails because  raw.githubusercontent.com ip is coming wrong

### ISSUE THREAD

**Issue by vkavitha** [redhat-developer/vscode-extension-tester#629]
### Discussed in https://github.com/redhat-developer/vscode-extension-tester/discussions/626

<div type='discussions-op-text'>

<sup>Originally posted by **vkavitha** February  9, 2023</sup>
Am trying to setup vscode-extension-tester in my MAC.

extest get-chromedriver                      
RequestError: connect ETIMEDOUT 2405:200:1607:2820:41::36:443
    at ClientRequest.<anonymous> (~/.nvm/versions/node/v19.0.0/lib/node_modules/vscode-extension-tester/node_modules/got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (~/.nvm/versions/node/v19.0.0/lib/node_modules/vscode-extension-tester/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:488:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1284:16)

Error is happening after when we followed instruction as in https://developers.redhat.com/blog/2019/11/18/new-tools-for-automating-end-to-end-tests-for-vs-code-extensions#writing_the_tests  

at the "launch the tests" step

using node v19.0.0 /  v16.19.0 /v18.14.0 behavior is same. 

Please help me understand the root cause of this issue and if there is a workaround to download and copy the chrome driver install in to the cache

</div>

**Comment by vkavitha** [comment]
Issue turned out to be because getting vscode manifest file for determining the matching chromium driver is being done by checking
https://raw.githubusercontent.com/Microsoft/vscode//cgmanifest.json

IP of raw.githubusercontent.com seems to be coming wrong

host [raw.githubusercontent.com](http://raw.githubusercontent.com/)
[raw.githubusercontent.com](http://raw.githubusercontent.com/) has address 49.44.79.236
[raw.githubusercontent.com](http://raw.githubusercontent.com/) has IPv6 address

but the working ip is 185.199.108.13 . Pls refer “[https://github.com/orgs/community/discussions/32889”](https://github.com/orgs/community/discussions/32889%E2%80%9D) for details

reporting here to see if there is a better solution
