### ISSUE TITLE
[Bug] get-chromedriver / get-vscode not working on Linux Arm64

### ISSUE THREAD

**Issue by gpsaraiva** [redhat-developer/vscode-extension-tester#743]
Hello,
I am running a Virtual box on a Mac M1, with a Ubuntu 22.04 Arm64. I am trying to run the vscode-extension-tester on the Ubuntu arm64 box.

When I try to download chromedriver or vscode, using the API functions (extest get-vscode -s <path> -c <version>), I am getting the error:

> e2e-tests@1.0.0 e2e-tests-get-vscode
> extest get-vscode "-s" "/home/gsaraiva/test-resources-db/" "-c" "1.76.2" "-t" "insider"

/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/@vscode/vsce/out/publish.js:50
                target = vsix.xmlManifest.PackageManifest.Metadata[0].Identity[0].$.TargetPlatform ?? undefined;
                                                                                                    ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/@vscode/vsce/out/api.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by gpsaraiva** [comment]
Sorry guys, I updated the node and npm version and I am not seeing this error anymore. But, the system architecture is not correct, when trying to download vscode from the ext-test get-vscode. Here's the error:

Downloading VSCode: 1.76.2 / stable
Downloading VS Code from: https://update.code.visualstudio.com/1.76.2/linux-ia32/stable
progress: 0/9 (0%)
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/got/dist/source/core/index.js:913:31)
    at Request._onResponse (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
progress: 0/9 (0%)
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/got/dist/source/core/index.js:913:31)
    at Request._onResponse (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.<anonymous> (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/home/gsaraiva/shell-plugins/gui/extension/tests/e2e/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)

It seems the architecture is ia32, when it should be arm64.
