### ISSUE TITLE
Workbench executeCommand() not working right after reloading windows

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-extension-tester#76]
I changed the helloworld-sample project tests so that the VS Code `Reload Window` command is being called in the middle:

```
    it('Hello World Command should show a notification with the correct text', async function () {
        this.timeout(8000);
        await new Workbench().executeCommand('hello world');
        let notification = await driver.wait(() => { return notificationExists('Hello'); }, 2000) as Notification;
        expect(await notification.getMessage()).equals('Hello World!');
        expect(await notification.getType()).equals(NotificationType.Info);

        await new Workbench().executeCommand('Reload Window');

        await new Workbench().executeCommand('hello world');
        notification = await driver.wait(() => { return notificationExists('Hello'); }, 2000) as Notification;
        expect(await notification.getMessage()).equals('Hello World!');
        expect(await notification.getType()).equals(NotificationType.Info);
    });
```
The `await new Workbench().executeCommand('hello world');` call after reloading windows causes an error:
```
 1) Hello World Example UI Tests
       Hello World Command should show a notification with the correct text:
     Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-workbench"}
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.4.18-1-MANJARO x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/x/Documents/work/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebDriver.findElement(By(css selector, .monaco-workbench))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:1014:17)
      at new AbstractElement (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:36:43)
      at new Input (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:18:1)
      at new QuickOpenBox (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:19:9)
      at Function.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:28:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-quick-open-widget))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElementPromise.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElementPromise.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:42:48)
      at new Input (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:18:1)
      at new QuickOpenBox (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:19:9)
      at Function.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:28:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

I think this may be because of some async call that isn't being caught, as explained here: 
https://github.com/redhat-developer/vscode-extension-tester/issues/42#issuecomment-562057841?

Are there any workarounds for this, other than using setTimeout?

I've tried `(await new Workbench().wait()).executeCommand('hello world');` and even:
```
await driver.wait(until.elementLocated(By.className('monaco-workbench')), 6000);
```
but no luck

**Comment by xorye** [comment]
Also, I am sometimes calling `await new Workspace().executeCommand('my command')` hangs, creating this error:

```
  1) Debug multiple project multiple workspace tests
       "after each" hook for "should debug Quarkus Maven projects in separate workspace folders":
     TimeoutError: Waiting until element is visible
Wait timed out after 5010ms
      at /Users/davidkwon/Documents/Github_Repositories/vscode-quarkus/node_modules/selenium-webdriver/lib/promise.js:2201:17
      at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
      at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
      at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
      at /Users/davidkwon/Documents/Github_Repositories/vscode-quarkus/node_modules/selenium-webdriver/lib/promise.js:2927:27
      at /Users/davidkwon/Documents/Github_Repositories/vscode-quarkus/node_modules/selenium-webdriver/lib/promise.js:668:7
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  From: Task: Waiting until element is visible
      at scheduleWait (node_modules/selenium-webdriver/lib/promise.js:2188:20)
      at ControlFlow.wait (node_modules/selenium-webdriver/lib/promise.js:2517:12)
      at Driver.wait (node_modules/selenium-webdriver/lib/webdriver.js:934:29)
      at QuickOpenBox.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:53:36)
      at Generator.next (<anonymous>)
      at /Users/davidkwon/Documents/Github_Repositories/vscode-quarkus/node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:4:12)
      at QuickOpenBox.wait (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:52:16)
      at Function.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:28:39)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Its quite strange because in this case, I did not reload any windows or close any workspaces.

**Comment by jrichter1** [comment]
Okay, the first problem is that the element does not exist yet after the reload. The elements' wait method can only wait for visibility, not existence, though. So using it is no good in this case. Luckily, there is a method in `VSBrowser` class that waits for workbench to load, I suggest you try it.
```typescript
const browser = VSBrowser.instance;
await browser.waitForWorkbench();
```

As for the second issue, it looks like the command prompt is not opening after sending F1. Or at least taking unbearably long to do so. I don't quite know what could cause this. Could you provide a reproducer for this?

**Comment by xorye** [comment]
Thank you for the suggestion. 

I've just tried it and I am getting two types of errors.
Sometimes I get a `StaleElementReferenceError`:
```
 1) Hello World Example UI Tests
       Hello World Command should show a notification with the correct text:
     Uncaught StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.4.18-1-MANJARO x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/x/Documents/work/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-quick-open-widget))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElementPromise.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElementPromise.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:42:48)
      at new Input (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:18:1)
      at new QuickOpenBox (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:19:9)
      at Function.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:28:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

And on other times I am getting a `NoSuchElementError`:
```
1) Hello World Example UI Tests
       Hello World Command should show a notification with the correct text:
     Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-workbench"}
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.4.18-1-MANJARO x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at /home/x/Documents/work/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/selenium-webdriver/lib/http.js:441:30
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebDriver.findElement(By(css selector, .monaco-workbench))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at Driver.findElement (node_modules/selenium-webdriver/lib/webdriver.js:1014:17)
      at new AbstractElement (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:36:43)
      at new Input (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:18:1)
      at new QuickOpenBox (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:19:9)
      at Function.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:28:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
  From: Task: WebElement.findElement(By(css selector, .monaco-quick-open-widget))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at WebElementPromise.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at WebElementPromise.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:42:48)
      at new Input (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/Input.js:18:1)
      at new QuickOpenBox (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:19:9)
      at Function.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:28:20)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/input/QuickOpenBox.js:5:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

For the second issue, I'll try to provide a small reproducer after I pinpoint when things go wrong.

**Comment by jrichter1** [comment]
I've made a few experiments with this case, and it looks like you actually need two waits to run it properly. The `waitForWorkbench` is still picking up elements before the window reloads, hence the wait ends prematurely. So you first need to wait until the workbench goes down.

Modifying the code you posted, hopefully this version will work:
```typescript
    let driver: WebDriver;
    let browser: VSBrowser;

    before(() => {
        browser = VSBrowser.instance;
        driver = VSBrowser.instance.driver;
    });

    it('Hello World Command should show a notification with the correct text', async function () {
        this.timeout(8000);
        await new Workbench().executeCommand('hello world');
        let notification = await driver.wait(() => { return notificationExists('Hello'); }, 2000) as Notification;
        expect(await notification.getMessage()).equals('Hello World!');
        expect(await notification.getType()).equals(NotificationType.Info);

        const workbench = new Workbench();
        await workbench.executeCommand('Reload Window');

        // wait for workbench to unload
        await driver.wait(until.stalenessOf(workbench));
        // wait for workbench to load up again
        await browser.waitForWorkbench();

        await new Workbench().executeCommand('hello world');
        notification = await driver.wait(() => { return notificationExists('Hello'); }, 2000) as Notification;
        expect(await notification.getMessage()).equals('Hello World!');
        expect(await notification.getType()).equals(NotificationType.Info);
    });
```
