### ISSUE TITLE
[Bug] chromedriver binary corrupted on initial install

### ISSUE THREAD

**Issue by whoismissing** [redhat-developer/vscode-extension-tester#879]
**Describe the bug** 
- When testing out `npm run ui-tests` for [helloworld-sample](https://github.com/redhat-developer/vscode-extension-tester/tree/main/sample-projects/helloworld-sample), an error occurs upon attempting to run the downloaded VS Code `code` binary with the `chromedriver`.
- It appears that the `chromedriver` binary gets corrupted upon initial unpack.
- As a workaround, simply unzipping `test-resources/chromedriver_linux64.zip` and running the tests again does the trick.

**Steps to Reproduce**
1. `git clone https://github.com/redhat-developer/vscode-extension-tester.git`
2. `cd vscode-extension-tester/sample-projects/helloworld-sample/`
3. `npm install`
4. `npm run ui-test`

```bash
$ npm run ui-test
> helloworld-sample@0.0.2 ui-test
> extest setup-and-run './out/ui-test/*-test.js' --code_settings settings.json --extensions_dir .test-extensions

Downloading VSCode: 1.80.0 / stable
Downloading VS Code from: https://update.code.visualstudio.com/latest/linux-x64/stable
progress: 0/134 (0%)
progress: 25444345/135325602 (18%)
progress: 50921462/135325602 (37%)
progress: 75169790/135325602 (55%)
progress: 94617595/135325602 (69%)
progress: 101662717/135325602 (75%)
progress: 119193599/135325602 (88%)
progress: 135184383/135325602 (99%)
progress: 135325602/135325602 (100%)
Downloaded VS Code into /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/test-resources/stable.tar.gz
Unpacking VS Code into /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/test-resources
Success!
Downloading ChromeDriver 108.0.5359.71 from: https://chromedriver.storage.googleapis.com/108.0.5359.71/chromedriver_linux64.zip
progress: 0/7297087 (0%)
progress: 7297087/7297087 (100%)
Unpacking ChromeDriver 108.0.5359.71 into /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/test-resources
Success!
Executing prepublish script 'npm run vscode:prepublish'...

> helloworld-sample@0.0.2 vscode:prepublish
> npm run compile


> helloworld-sample@0.0.2 compile
> tsc -p ./ && npm run lint


> helloworld-sample@0.0.2 lint
> eslint src --ext .ts

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============
 DONE  Packaged: /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/helloworld-sample-0.0.2.vsix (58 files, 52.44KB)
Installing extensions...
(node:31191) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `code --trace-deprecation ...` to show where the warning was created)
Extension 'helloworld-sample-0.0.2.vsix' was successfully installed.
Loading mocha configuration from /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/.mocharc.js


Detected user defined code settings
Writing code settings to /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/test-resources/settings/User/settings.json
Launching browser...
  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (31ms)
  2 failing

  1) "before all" hook in "{root}":
     Error: Server terminated early with status 2
      at /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/selenium-webdriver/remote/index.js:260:24
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) "after all" hook in "{root}":
     TypeError: Cannot read properties of undefined (reading 'manage')
      at VSBrowser.<anonymous> (node_modules/vscode-extension-tester/out/browser.js:129:48)
      at Generator.next (<anonymous>)
      at /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/vscode-extension-tester/out/browser.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/browser.js:4:12)
      at VSBrowser.quit (node_modules/vscode-extension-tester/out/browser.js:128:16)
      at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:82:35)
      at Generator.next (<anonymous>)
      at /home/user/Downloads/git/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/vscode-extension-tester/out/suite/runner.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/suite/runner.js:4:12)
      at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:80:24)
```

**Expected behavior**

```bash
$ cd test-resources/
$ file chromedriver
chromedriver: data
$ sha256sum chromedriver
e5965af180ab58f1826227c4c20ed6fd41467d8d68224662bc125daa28331909  chromedriver
$ unzip chromedriver_linux64.zip
Archive:  chromedriver_linux64.zip
replace chromedriver? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: chromedriver
$ file chromedriver
chromedriver: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=0d53bee98466bf700e207352cc41b40dd7d5f8c8, stripped
$ sha256sum chromedriver
cbcbb00b9adfa529e23927135c0ea70abc4744761b5f2997b478e47cb0f0523c  chromedriver
```

**Environment information**
 - OS:
    - [ ] Windows
    - [x] Linux Ubuntu 20.04
    - [ ] macOS
- VSCode version:  1.80.0
- ExTester version:  5.8.0
- npm version:  `npm --version` `9.6.3
- Node version: `node --version` `v19.9.0`

**Attachments**
> If applicable, add screenshots, logs, examples... to help explain your problem.

**Comment by djelinek** [comment]
@whoismissing Hello, thank you for your time and new detailed issue. I noticed you are using Node 19. The extester is currently supports only Node 16. Are you having this issue also with Node 16?

**Comment by microhobby** [comment]
Interesting, I was using the v18 LTS and I was getting the same return from @whoismissing , using the v16 fixed it :)

**Comment by LuboTerifaj** [comment]
Hi @whoismissing , @djelinek , @microhobby ,

the issue "chromedriver binary being corrupted after unzipping" is present since Node 18.16.0 version. Using node-unzipper, chromedriver is being unzipped successfully only with Node 18.5.0 version and lower.

 See also https://github.com/ZJONSSON/node-unzipper/issues/271 for more information.

Thanks!

**Comment by djelinek** [comment]
closing - We are supporting only Node 16 currently.

**Comment by DavyLandman** [comment]
I want to share that we switched to https://www.npmjs.com/package/yauzl to extract in pure node.
