### ISSUE TITLE
Notification.takeAction fails with NoSuchElementError:

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#88]
I have some trouble with the `takeAction` function from the Notification class: https://github.com/redhat-developer/vscode-extension-tester/blob/a153e8d45c668219cb66f572ef7113552421c1d1/src/webdriver/components/workbench/Notification.ts#L89

Instead of the action being taken, I get the following error:
```
     Uncaught NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//a[@role='button' and @title='Yes']"}
  (Session info: chrome=76.0.3809.146)
  (Driver info: chromedriver=76.0.3809.126 (d80a294506b4c9d18015e755cee48f953ddc3f2f-refs/branch-heads/3809@{#1024}),platform=Linux 5.6.0-1-default x86_64)
      at Object.checkLegacyResponse (node_modules/selenium-webdriver/lib/error.js:546:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:509:13)
      at doSend.then.response (node_modules/selenium-webdriver/lib/http.js:441:30)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  From: Task: WebElement.findElement(By(xpath, .//a[@role='button' and @title='Yes']))
      at Driver.schedule (node_modules/selenium-webdriver/lib/webdriver.js:807:17)
      at CenterNotification.schedule_ (node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
      at CenterNotification.findElement (node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
      at new AbstractElement (node_modules/vscode-extension-tester/out/webdriver/components/AbstractElement.js:42:48)
      at new NotificationButton (node_modules/vscode-extension-tester/out/webdriver/components/workbench/Notification.js:135:9)
      at CenterNotification.<anonymous> (node_modules/vscode-extension-tester/out/webdriver/components/workbench/Notification.js:95:36)
      at Generator.next (<anonymous>)
      at fulfilled (node_modules/vscode-extension-tester/out/webdriver/components/workbench/Notification.js:5:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

My test code looks roughly like this:
``` Typescript
    const actions = await notification[0].getActions();
    expect(actions.map((act) => act.getTitle())).to.deep.equal(["Yes", "No"]);
    await notification[0].takeAction("Yes");
```
So the action with the label "Yes" should exist, nevertheless, I get the above error.

**Comment by jrichter1** [comment]
I'm struggling to reproduce this, even added a simple test using this code and it seems to be passing. Don't really know what's going on here. Maybe you could check if the screenshot reveals anything. Failed tests should produce screenshots to `test-resources/screenshots`.

**Comment by dcermak** [comment]
I've taken another look at that and it turns out that if I remove the first two lines from my snippet and end up with this only:
``` typescript
    const notifications = await center.getNotifications(NotificationType.Any);

    const notification = await removeMsTelemetryNotification(notifications);
    // omitting checks whether notification is correct here

    // const actions = await notification[0].getActions();
    // expect(actions.map((act) => act.getTitle())).to.deep.equal(["Yes", "No"]);

    await notification[0].takeAction("Yes");
    // do more stuff after the action is taken
```
then it works!

Could it be that the `notification[0].getActions()` "consumes" the notification somehow?

**Comment by jrichter1** [comment]
`getActions` contains no code that would manipulate elements, I don't think it is related to the problem.

Is the notification still present by the time `takeAction` is called in the original code? If this call fails, it should generate a screenshot you can check.

If instead of the commented code, you'd add a short wait, would it fail in the same way?

**Comment by dcermak** [comment]
> `getActions` contains no code that would manipulate elements, I don't think it is related to the problem.
> 
> Is the notification still present by the time `takeAction` is called in the original code? If this call fails, it should generate a screenshot you can check.
> 
> If instead of the commented code, you'd add a short wait, would it fail in the same way?

I have added a short wait into the `removeMsTelemetryNotification` function and the issue seems to be gone now (the tests still occasionally fail, but most of the time they actually pass). Sorry for this invalid issue and thank you for your time!

And btw, thank you for making me aware of the screenshot feature! I totally didn't know that existed and it is a huge life saver :+1:
