### ISSUE TITLE
Workbench.executeCommand() appears to be broken with vscode 1.44.0

### ISSUE THREAD

**Issue by dcermak** [redhat-developer/vscode-extension-tester#90]
VSCode got an update 2 days ago and my integration tests suddenly started to fail with very obscure errors: commands no longer appear to get entered at all. My tests work fine with vscode 1.43, but in 1.44 `Workbench.executeCommand()` doesn't do a thing: the command prompt opens, but no text is entered.

Is this just me or did something in VSCode change?

**Comment by apupier** [comment]
same issue observed on wsdl2rest project https://travis-ci.org/github/camel-tooling/vscode-wsdl2rest/builds/672854212#L1197-L1202

```
(node:6235) UnhandledPromiseRejectionWarning: AssertionError: expected '' to equal 'WSDL URL (Press \'Enter\' to confirm or \'Escape\' to cancel)'
    at Input.<anonymous> (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-uitests-tooling/out/components/Input.js:148:59)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-uitests-tooling/out/components/Input.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by mlorinc** [comment]
It seems like QuickOpenBox was replaced in favor of InputBox in following commit  [quick access - first cut old quick open removal](https://github.com/microsoft/vscode/commit/f6fba38e9a43df3a1b90f26cad89da19562db13c#diff-c02cf513977a6cd2cb7ff59a89e5d8c6).
