### ISSUE TITLE
[🚫 Bug] Tests hang after loading mocha configurations

### ISSUE THREAD

**Issue by madushajg** [redhat-developer/vscode-extension-tester#945]
> Define the issue title **short** and **most specific** to the problem.

When trying to run the [helloworld-sample](https://github.com/redhat-developer/vscode-extension-tester/tree/main/sample-projects/helloworld-sample) it hangs at the 'Loading mocha configuration from..' and didn't start the tests.

```
$ npm run ui-test                                                           

> helloworld-sample@0.0.2 ui-test
> extest setup-and-run './out/ui-test/*-test.js' --code_settings settings.json --extensions_dir .test-extensions

Downloading VSCode: 1.82.2 / stable
Downloading VS Code from: https://update.code.visualstudio.com/latest/darwin/stable
Downloaded VS Code into /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/test-resources/stable.zip
Unpacking VS Code into /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/test-resources
Success!
Downloading ChromeDriver 114.0.5735.90 from: https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac64.zip
progress: 0/8693987 (0%)
progress: 4706798/8693987 (54%)
progress: 8693987/8693987 (100%)
Unpacking ChromeDriver 114.0.5735.90 into /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/test-resources
Success!
Executing prepublish script 'npm run vscode:prepublish'...

> helloworld-sample@0.0.2 vscode:prepublish
> npm run compile


> helloworld-sample@0.0.2 compile
> tsc -p ./ && npm run lint


> helloworld-sample@0.0.2 lint
> eslint src --ext .ts

 DONE  Packaged: /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/helloworld-sample-0.0.2.vsix (58 files, 52.43KB)

Installing extensions...
(node:30906) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'helloworld-sample-0.0.2.vsix' was successfully installed.
Loading mocha configuration from /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/.mocharc.js


  1) "before all" hook in "{root}"
  2) "after all" hook in "{root}"

  0 passing (3m)
  2 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) "after all" hook in "{root}":
     TypeError: Cannot read properties of undefined (reading 'manage')
      at VSBrowser.<anonymous> (node_modules/vscode-extension-tester/out/browser.js:152:48)
      at Generator.next (<anonymous>)
      at /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/vscode-extension-tester/out/browser.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/browser.js:27:12)
      at VSBrowser.quit (node_modules/vscode-extension-tester/out/browser.js:151:16)
      at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:108:35)
      at Generator.next (<anonymous>)
      at /Users/abc/repositories/vscode-extension-tester/sample-projects/helloworld-sample/node_modules/vscode-extension-tester/out/suite/runner.js:31:71
      at new Promise (<anonymous>)
      at __awaiter (node_modules/vscode-extension-tester/out/suite/runner.js:27:12)
      at Context.<anonymous> (node_modules/vscode-extension-tester/out/suite/runner.js:106:24)

```

**Environment information**
 - OS:
    - [ ] Windows
    - [ ] Linux
    - [x] macOS 13.5.1 (22G90) (arm64)
- VSCode version:  `1.82.2`
- ExTester version:  `5.9.1`
- Node (npm) version:  node: `v16.20.2` npm: `8.19.4`

**Comment by djelinek** [comment]
Hello @madushajg 
thank you for reporting the issue! unfortunately I am not able to reproduce locally 🙁 

My only blind shot would be.. does the `sample-projects` or `sample-projects/helloworld-sample` folder some weird corrupted socket file which was not present there before you firstly run the tests?

eg something like that?
![image](https://github.com/redhat-developer/vscode-extension-tester/assets/18696866/ba33e465-1170-4602-86ed-aeede326baba)

in case you will find some file with question mark, you can try to delete it and run tests.. it could help

**Comment by madushajg** [comment]
@djelinek I checked the directory structure and there is no any additional directories present

**Comment by djelinek** [comment]
we were able to reproduce your issue. Could you please change test resources directory to some shorter location then the root of the `helloworld-sample` project?

you can for example add `--storage /tmp/test-resources` at the and of `ui-test` script inside `package.json`

Relates to #485 
This bug was already fixed and will be delivered in next release.
