### ISSUE TITLE
[Bug] NoSuchElementError: no such element: Unable to locate element

### ISSUE THREAD

**Issue by sgotko** [redhat-developer/vscode-extension-tester#955]
Same as  [this ](https://github.com/redhat-developer/vscode-extension-tester/issues/472)

Issue is still actual for me.
Code like this: 
```javascript
  const editorView = new EditorView();
  await editorView.openEditor('Webview title');
  const webview = new WebView();
  await webview.switchToFrame();
```
Causes this:
```shell
NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":".//div[starts-with(@id, 'webview-editor')]"}
  (Session info: chrome=108.0.5359.215)
      at Object.throwDecodedError (node_modules\selenium-webdriver\lib\error.js:524:15)
      at parseHttpResponse (node_modules\selenium-webdriver\lib\http.js:601:13)
      at Executor.execute (node_modules\selenium-webdriver\lib\http.js:529:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules\selenium-webdriver\lib\webdriver.js:745:17)
``` 

**Environment information**
 - OS:
    - [x ] Windows
    - [x] Linux
    - [ ] macOS
- VSCode version: 1.81.1
- ExTester version:  ???
- Node (npm) version: node 16, npm 9.8.1

**Comment by djelinek** [comment]
Hello, are you still facing the same issue? 

could you please provide more context? maybe to provide some screenshots or full test you are trying to execute? I have no reproducer for this issue unfortunately.

**Comment by djelinek** [comment]
Closing, in case of still hitting same problem - feel free to reopen

you can use PageObject `WebviewView` for webviews implemented for SideBar or BottomBar - see [Wiki](https://github.com/redhat-developer/vscode-extension-tester/wiki/WebviewView)

or use PageObject `WebView` for webviews implemented for editor - see [Wiki](https://github.com/redhat-developer/vscode-extension-tester/wiki/WebView)

_Note: WebviewView is available from extester release_ `v6.0.0`

**Comment by JoshwinThomasIBM** [comment]
I'm facing similar issue , when i try to access an element from the HTML that is rendered in the web view i'm receiving the error as no such element . I verified using dev tools if the element is available and it is . Also from the dev tools console i tried to access the element by id and was able to access.

const webview =  new WebView();
webview.switchToFrame();
const element = await webview.findElement(By.xpath("//div[@id=testId]"));

 NoSuchElementError: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@id=reportPathTest]"}
