### ISSUE TITLE
[🚀 Request] Support latest NodeJS LTS

### ISSUE THREAD

**Issue by djelinek** [redhat-developer/vscode-extension-tester#975]
### Describe the request

Currently we are not supporting latest NodeJS LTS because it is not working properly. The Node 18.15 is the more recent version which is working. The limitation comes from `selenium-webdriver` dependency which support NodeJS policy is only a `best effort` for new releases. (for details see https://www.npmjs.com/package/selenium-webdriver#node-support-policy).

### Usage

use vscode-extension-tester with latest NodeJS LTS versions

**Comment by apupier** [comment]
Current state for investigation:
- modified Selenium upstream to use 18.15+
- same issue was reported by someone else a long time ago when using an Electron application

to continue investigation: Write a selenium test with the simplest Electron application and launch with different Node version

**Comment by apupier** [comment]
Current error when building with 18.15+ strict:

```
   1) "before all" hook in "{root}":
     Error: Server terminated early with status 2
      at /home/runner/work/vscode-extension-tester/vscode-extension-tester/node_modules/selenium-webdriver/remote/index.js:256:70
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by apupier** [comment]
sounds like the problem with Node 18.15+ lies during the extract of the chromedriver
if I pick the compressed folder downloaded, do an extract on my machine I can start the chromedriver
if I pick the chromedriver extracted using Node 18.15+, I have an exec format error

tried using https://github.com/redhat-developer/vscode-extension-tester/actions/runs/8002430507/job/21855644150?pr=1143

**Comment by apupier** [comment]
VS Code itself is still on Node 18.x https://github.com/microsoft/vscode/blob/078596ba3bee4e1ba65e242b7bb4aa8e3f9aa2c0/build/npm/preinstall.js#L13 so I guess we should test with latest 18.x for now. Maybe we can add one config to test with 20.x (active LTS) and 21.x (latest)

**Comment by swathisuja** [comment]
get-chromedriver fails with below error     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
PS D:\MPLAB PRO Extension Tester\mplabng-tester> npm run get-chromedriver

> mplabng-tester@0.0.1 get-chromedriver
> extest get-chromedriver -c 1.87.2 -s D:\test_reources


ERROR:  You are using the unsupported NodeJS version '21.7.1'. The latest supported version is '18.15.0'.
        We recommend to use supported version to have ExTester working properly.
        More info at https://github.com/redhat-developer/vscode-extension-tester/issues/975


(node:16076) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (file:///D:/MPLAB%20PRO%20Extension%20Tester/mplabng-tester/node_modules/got/dist/source/core/index.js:706:31)
    at Request._onResponse (file:///D:/MPLAB%20PRO%20Extension%20Tester/mplabng-tester/node_modules/got/dist/source/core/index.js:768:24)
    at ClientRequest.<anonymous> (file:///D:/MPLAB%20PRO%20Extension%20Tester/mplabng-tester/node_modules/got/dist/source/core/index.js:786:23)
    at Object.onceWrapper (node:events:634:26)
    at ClientRequest.emit (node:events:531:35)
    at HTTPParser.parserOnIncomingClient (node:_http_client:698:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:540:22)
    at TLSSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
PS D:\MPLAB PRO Extension Tester\mplabng-tester> 

Despite having node 18.15.0 installed and mentioned in json file. Any help to proceed with chromedriver isntallation?

**Comment by apupier** [comment]
Please try to use a more recent version of vscode-extension-tester such as the 7.2.0 where there is no more this limitation.
