### ISSUE TITLE
Return an error code when the extension installation is failing

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-extension-tester#98]
use case:
- have an extension which requires version 1.x of VS COde
- try to launch with specific code_version 1.y with x > y

currently, the installation of the extension is failing but the return code is 0. it leads CI to not detect the failure.

For instance:
https://travis-ci.org/github/camel-tooling/vscode-wsdl2rest/builds/674880592#L1198-L1214

```
Installing extensions...
Unable to install extension 'redhat.vscode-wsdl2rest' as it is not compatible with VS Code '1.43.2'.
Failed Installing Extensions: /home/travis/build/camel-tooling/vscode-wsdl2rest/vscode-wsdl2rest-0.0.12.vsix
(node:6294) UnhandledPromiseRejectionWarning: Error: Command failed: ELECTRON_RUN_AS_NODE=1 "/home/travis/build/camel-tooling/vscode-wsdl2rest/test-resources/VSCode-linux-x64/code" "/home/travis/build/camel-tooling/vscode-wsdl2rest/test-resources/VSCode-linux-x64/resources/app/out/cli.js" --install-extension "/home/travis/build/camel-tooling/vscode-wsdl2rest/vscode-wsdl2rest-0.0.12.vsix"
    at checkExecSyncError (child_process.js:630:11)
    at Object.execSync (child_process.js:666:15)
    at CodeUtil.installExtension (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/util/codeUtil.js:112:23)
    at ExTester.<anonymous> (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:107:30)
    at Generator.next (<anonymous>)
    at /home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:4:12)
    at ExTester.installVsix (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:86:16)
    at ExTester.<anonymous> (/home/travis/build/camel-tooling/vscode-wsdl2rest/node_modules/vscode-extension-tester/out/extester.js:135:24)
(node:6294) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:6294) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
The command "npm run ui-test --silent" exited with 0.
```

**Comment by jrichter1** [comment]
Fixed in 2.6.0
