### ISSUE TITLE
[🚫 Bug] BottomBarPanel().openOutputView() no such element: Unable to locate element

### ISSUE THREAD

**Issue by microhobby** [redhat-developer/vscode-extension-tester#991]
### Describe the bug

When using: 

```js
new BottomBarPanel().openOutputView();
```

I'm getting the exception:

```
(Session info: chrome=114.0.5735.289)
no such element: Unable to locate element: {"method":"css selector","selector":".panel-switcher-container"}
```

This started after the update to VS Code `v1.84`

### Steps to reproduce

```Shell
1. Create a test that uses the `BottomBarPanel().openOutputView();`
```

### Logs

```Shell
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".panel-switcher-container"}
  (Session info: chrome=114.0.5735.289)
    at Object.throwDecodedError (<removed>/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (<removed>/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (<removed>/node_modules/selenium-webdriver/lib/http.js:529:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (<removed>/node_modules/selenium-webdriver/lib/webdriver.js:745:17) {name: 'NoSuchElementError', remoteStacktrace: '#0 0x55a3e0bd84e3 <unknown>
#1 0x55a3e09…<unknown>
#20 0x7fe848c8f6ba <unknown>
', stack: 'NoSuchElementError: no such element: Unable t…s/selenium-webdriver/lib/webdriver.js:745:17)', message: 'no such element: Unable to locate element: {…er"}
  (Session info: chrome=114.0.5735.289)'}
```

### Operating System

Ubuntu 23.04

### Visual Studio Code

1.84

### vscode-extension-tester

5.10

### NodeJS

v16.20.2

### npm

8.19.4

**Comment by c3danielxu** [comment]
I am also encountering a similar issue with `await new BottomBarPanel().openDebugConsoleView();`, also after upgrading to latest VS Code version of 1.84.

**Comment by djelinek** [comment]
thank you for reporting the issue. I have reproduced the bug.

It will be fixed in upcoming release with support for VS Code 1.84.x
